#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Performs commands for each connected Android device
#?? 0.1.0
##?
##? Usage:
##?    devices
##?    devices api
##?    devices prop <property>
##?    devices install <path>
##?    devices uninstall <package>
##?    devices clear <package>
##?    devices link <uri>
##?
##? Options:
##?     prop <property>       Displays a property
##?     install <path>        Installs and APK given its path
##?     uninstall <package>   Uninstalls an application package
##?     clear <package>   	  Clear data given an application package
##?     link <uri>   	  	  Dispatches a deep-link

docs::eval "$@"

devices() {
   adb devices | tail -n +2 | cut -sf -1
}

if $api; then
   prop="ro.build.version.release"
fi

if $prop && [ -n $property ]; then
   devices | xargs -I % adb -s % shell getprop "$property"
elif $install && [ -n $path ]; then
   devices | xargs -I % adb -s % install -r "$path"
elif $uninstall && [ -n $package ]; then
   devices | xargs -I % adb -s % uninstall "$package"
elif $clear && [ -n $package ]; then
   devices | xargs -I % adb -s % shell pm clear "$package"
elif $link && [ -n $uri ]; then
   devices | xargs -I % adb -s % shell am start "$uri"
else
   devices
fi
