#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/environment/core.sh"

##? Performs operation on an Android emulator
#?? 0.2.1
##?
##? Usage:
##?    emulator [list]
##?    emulator start [--newest]
##?
##? Options:
##?    start          Prompts for an emulator and launch it
##?    start newest   Starts the emulator with the most recent API

docs::eval "$@"

function emulator() {
   "$ANDROID_HOME/tools/emulator" "$@"
}

function newest_emulator() {
   local emulators="$1"
   local newest_api="$(echo "$emulators" | awk -F 'API_' '{print $2}' | sort -r | head -n1 \
      || echo "$emulators" | head -n1)"
   echo "$emulators" | grep "$newest_api" | head -n1
}

function start_emulator() {
   local identifier="$1"
   emulator -avd "$identifier" -netdelay none -netspeed full &
   disown
}

function start_newest_emulator() {
   local emulators="$1"
   start_emulator "$(newest_emulator "$emulators")"
}

function prompt_and_start_emulator() {
   local emulators="$1"
   local identifier=$(echo "$emulators" | fzf-tmux --reverse --height 25%)
   start_emulator "$identifier"
}

emulators="$(emulator -list-avds)"

if $start; then
   $newest \
      && start_newest_emulator "$emulators" \
      || prompt_and_start_emulator "$emulators"
else
   echo "$emulators"
fi
