#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Send files via FTP
#?? 0.2.1
##?
##? Usage:
##?    ftp send <filepath>

docs::eval "$@"

HOST='192.168.15.10'
PORT=2121
USER='anonymous'
PASSWD=''

ftp -n $HOST $PORT <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
put "$filepath"
quit
END_SCRIPT
