#!/usr/bin/env bash
set -uo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Get info about connected USB devices
##?
##? Usage:
##?    usb ls
##?    usb info
##?    usb compile
##?    usb manufacturer-check

doc::maybe_help "$@"

USB_DIR="${DOTFILES}/termux/usb"

remove_last_comma() {
   sed '$s/,$//'
}

list_devices() {
   termux-usb -l
}

list_devices_raw() {
   list_devices | jq -r '.[]'
}

ask_for_permission() {
   termux-usb -r "$1"
}

get_info() {
   ask_for_permission "$1"
   cd "$USB_DIR"
   termux-usb -e ./usbtest "$1"
}

get_info_json() {
   cd "$USB_DIR"
   echo '{'
   get_info "$1" | sed -E 's/^([^:]+): (.*)/"\1":"\2",/' | remove_last_comma
   echo '}'
}

get_info_all() {
   for id in $(list_devices_raw); do
     get_info "$id" 
   done
}

contains_manufacturer() {
   get_info_all \
      | grep 'Manuf' \
      | grep -q "$@"
}

compile() {
   cd "$USB_DIR"
   gcc usbtest.c -lusb-1.0 -o usbtest
}

main() {
   local -r cmd="${1:-}"
   shift
   case $cmd in
      l|ls|list) list_devices ;;
      i|info) get_info_all "$@" ;;
      r) ask_for_permission "$@" ;;
      c*) compile ;;
      m|*manuf*) contains_manufacturer "$@" ;;
      *) exit 2 ;;
   esac
}

main "$@"