#!/usr/bin/env bash

# absolute path to the directory to use when loading a plugin
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

# monitor the specified plugin_dir and automatically reload any *.so
chunkc core::hotload 0
 
# global configs
chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     18
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     0

# offset and gap incremental step
chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

# bsp
chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5
chunkc set window_region_locked          1

# focus
chunkc set window_focus_cycle            all
chunkc set mouse_follows_focus           1

# float
chunkc set window_float_next             0
chunkc set window_float_center           1

# mouse interaction
chunkc set mouse_modifier                fn

# chwm-sa (not used at the moment)
chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.5

# chunkwm-border 
chunkc set focused_border_color          0xffc0b18b
chunkc set focused_border_width          4
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  0
chunkc set preselect_border_color        0xffffff00
chunkc set preselect_border_width        4
chunkc set preselect_border_radius       0

# load plugins
chunkc core::load tiling.so
# chunkc core::load border.so
# chunkc core::load ffm.so

# Rules
chunkc tiling::rule --owner \"System Preferences\" --subrole AXStandardWindow --state tile
chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner iTerm2 --subrole AXDialog --state tile
chunkc tiling::rule --owner kitty --subrole AXDialog --state tile
chunkc tiling::rule --owner \"qemu-system-x86_64\" --state float
#chunkc tiling::rule --owner Emacs --state tile --desktop 8
chunkc tiling::rule --owner Emacs --state tile --desktop 8
#chunkc tiling::rule --owner \"Google Chrome\" --desktop 2
#chunkc tiling::rule --owner \"Sublime Text\" --desktop 3
chunkc tiling::rule --owner Spotify --desktop 5
chunkc tiling::rule --owner Slack --desktop 6
