#!/usr/bin/env bash
# vim: filetype=sh

# if [ -t 1 ]; then
#    exec zsh
# fi

# dotfiles
export DOTFILES="${DOTFILES:-$HOME/.dotfiles}"

# load vars
source "${DOTFILES}/shell/aux/vars.sh"

# load helper functions
source "${DOTFILES}/shell/aux/core.zsh"

# load aliases
source "${DOTFILES}/shell/aliases/core.sh"
source "${DOTFILES}/shell/aliases/git_fallback.zsh"

# set prompt
export PS1="\n\[\e[32m\]\w\[\e[m\] \[\e[31m\]$(nonzero_return)\[\e[m\]\n\[\e[33m\]\\$\[\e[m\] "

# load local custom config
source "${DOTFILES}/local/zshrc"

# fzf
if ${DOT_FZF:-false}; then
   source "${HOME}/.fzf.bash" || true
fi

# fasd
if ${DOT_FASD:-false}; then
   eval "$(lua "${DOTFILES}/modules/z.lua/z.lua" --init bash enhanced once)"
fi
