export DOTFILES=$HOME/.dotfiles

# antigen
source $DOTFILES/modules/antigen/antigen.zsh
export _ANTIGEN_CACHE_ENABLED=true 
antigen init $DOTFILES/shell/antigenrc

source $DOTFILES/shell/functions.zsh
source $DOTFILES/shell/aliases.zsh
source $DOTFILES/shell/plugins.zsh

include ~/.fzf.zsh
include ~/.localrc
