# set environment
export DOTFILES=$HOME/.dotfiles
export ZPLUG_HOME="${DOTFILES}/modules/zplug"

# load plugins
source $DOTFILES/shell/plugins/zplug.zsh

# setup plugins
source $DOTFILES/shell/plugins/config.zsh

# set editor
export EDITOR='nvim'

# load aliases and helper functions
source $DOTFILES/shell/aliases/browsing.zsh
source $DOTFILES/shell/aliases/coding.zsh
source $DOTFILES/shell/aliases/general.zsh
source $DOTFILES/shell/aliases/tmux.zsh
source $DOTFILES/shell/aliases/git.zsh

# setup key bindings
source $DOTFILES/shell/bindings/fzf.zsh

# load local custom config
include $DOTFILES/local/zshrc

# add folders to PATH
export PATH="$DOTFILES/local/bin:$DOTFILES/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
