#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Shows mission control space info
#?? 0.1.0
##?
##? Usage:
##?    spaces

docs::eval "$@"

spaces="$(defaults read com.apple.spaces)"

echo "$spaces" \
   | grep -n 'paces =' \
   | awk '{print $1}' \
   | sed 's/.$//'

echo "$spaces" \
   | sed -n '73,9999p'

# | grep -zP "paces\s*=.*?\((.*?)"

# \s*=.*?\((.*?)\)
