#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Shows weather info
 #? 0.1.0
##?
##? Usage:
##?    weather [<location>]

docs::eval "$@"

_format() {
  echo "$@" | grep -v "New feature" | grep -v Follow
}

coll::is_empty ${location:-""} \
	&& _format "$(curl -s "wttr.in/Sao_Paulo")" \
	|| _format "$(curl -s "wttr.in/$location")"