#!/usr/bin/env bash

set -e

CONFIG="conf.yaml"
DOTBOT_DIR="modules/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Updating submodules..."
(git pull && git submodule init && git submodule update && git submodule status && \
  cd "${BASEDIR}" && git submodule update --init --recursive "${DOTBOT_DIR}") > /dev/null

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"


