#!/usr/bin/env bash
# vim: filetype=sh
# set -uo pipefail

# source "${DOTFILES}/scripts/core/main.sh"

##? Remove containers
#?? 0.1.0
##?
##? Usage:
##?    rm

# docs::eval "$@"

dot docker stop
docker rm $(docker ps -aq)
