#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/documentation.sh"

##? Remove containers
#?? 0.1.0
##?
##? Usage:
##?    rm
##?    rm images

docs::eval "$@"

dot docker stop || true

if $images; then
  docker rmi $(docker images -q) --force
else
  docker rm $(docker ps -aq)
fi
