#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/documentation.sh"

##? Remove containers
#?? 0.1.0
##?
##? Usage:
##?    rm

docs::eval_help "$@"

dot docker stop
docker rm $(docker ps -aq)
