#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/documentation.sh"

##? Stop containers
#?? 0.1.0
##?
##? Usage:
##?    stop

docs::eval_help "$@"

docker stop $(docker ps -aq)
