#!/usr/bin/env bash

source "${DOTFILES}/scripts/git/aux/core.sh"
source "${DOTFILES}/scripts/git/aux/changelog.sh"

##? Changelog generator
##?
##? Usage:
##?    log release
##?    log commit

docs::eval "$@"

git::changelog_commit() {
   cd "$(git::root)"

   local -r changes="$(git diff --numstat HEAD \
      | awk '{print $3" "$1-$2}' \
      | sort -k2 -n -r \
      | awk '{print $1}' \
      | sed -E 's|(.*)/(.*)|\2|g')"

   local -r n="$(printf "$changes" \
      | wc -l \
      | xargs)"

   local msg="$(printf "$changes" \
      | head -n3 \
      | tr '\n' ';' \
      | sed -E 's/ *; */, /g')"

   [[ $n -gt 3 ]] && msg="${msg}..."

   echo "$(date +'%b-%d %Hh%M'): ${msg}"
}

if $release; then
   git::changelog_release "$@"
elif $commit; then
   git::changelog_commit "$@"
fi