#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/git.sh"

##? Interactive git checkout
#?? 0.1.0
##?
##? Usage:
##?    checkout

_checkout() {
   local tags branches target
   tags=$(
    git tag | awk '{print "\x1b[31;1mtag\x1b[m\t" $1}') || return
   branches=$(
    git branch --all --sort=committerdate | grep -v HEAD  |
    sed "s/.* //"    | sed "s#remotes/[^/]*/##" |
    awk '{print "\x1b[34;1mbranch\x1b[m\t" $1}') || return
   target=$(
    (echo "$tags"; echo "$branches") | sort -u | grep . | tac |
    fzf-tmux --query="$1" --multi --select-1 --exit-0 --reverse --height 25% -- --no-hscroll --ansi +m -d "\t" -n 2 -1 -q "$*") || return
   git checkout $(echo "$target" | awk '{print $2}')
}

_checkout