#!/usr/bin/env bash

source "${DOTFILES}/scripts/git/aux/core.sh"

##? Git commit helpers
##?
##? Usage:
##?    commit am <args>...

_msg() {
   if [[ $# -gt 0 ]] && [[ "${1:-}" != "wip" ]]; then
      echo "$*"
   else
      dot git changelog commit
   fi
}

_am() {
   git add . || true
   shift
   msg="$(_msg "$@" || echo "WIP")"
   git commit -am "$msg"
}

cmd="${1:-}"
case $cmd in
   am) _am "$@" ;;
   *) doc::help_or_fail "$@" ;;
esac
