#!/usr/bin/env bash

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/git/aux/core.sh"
source "${DOTFILES}/scripts/core/str.sh"

##? PR utilities
##?
##? Usage:
##?   pr preview

doc::maybe_help "$@"

_cleanup_uri() {
   echo "$1" \
      | sed 's/git@//g' \
      | sed 's/\.git//g' \
      | sed 's|:|/|g'
}

_full_uri() {
   local -r uri="$1"
   local -r branch="$2"
   echo "https://${uri}/compare/${branch}?expand=1"
}

_get_url() {
   cd "$(git::root)"
   cd .git
   local -r original_uri="$(cat config \
      | grep "remote \"origin" -A2 \
      | grep github \
      | str::last_word)"
   local -r uri="$(_cleanup_uri "$original_uri")"
   local -r branch="$(git::current_branch)"
   _full_uri "$uri" "$branch"
}

dot system open "$(_get_url)"
