#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/git.sh"
source "${DOTFILES}/scripts/git/aux/hooks.sh"

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
git::prompt_if_protected "$current_branch" "master"
