#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/git.sh"

##? Git pull helpers
#?? 0.1.0
##?
##? Usage:
##?    pull module <args>...
##?    pull master <args>...

_master() {
   git checkout master 
   git pull 
   git checkout - 
   git merge master 
   git checkout -v -a
}

_module() {
   git pull 
   git submodule init 
   git submodule update 
   git submodule status
}

cmd="$1"
shift

case $cmd in
   master) _master "$@";;
   *module) _module "$@";;
esac
