#!/usr/bin/env bash
 
source "${DOTFILES}/scripts/git/aux/core.sh"

##? Git pull helpers
##?
##? Usage:
##?    pull module <args>...
##?    pull master <args>...

docs::eval_help "$@"

_master() {
   git checkout master
   git pull
   git checkout -
   git merge master
   git checkout -v -a
}

_module() {
   git pull
   git submodule init
   git submodule update
   git submodule status
}

cmd="$1"
shift

case $cmd in
   master) _master "$@" ;;
   *module) _module "$@" ;;
esac
