#!/usr/bin/env bash

source "${DOTFILES}/scripts/git/aux/core.sh"

##? Git pull helpers
##?
##? Usage:
##?    pull module <args>...
##?    pull master <args>...

doc::maybe_help "$@"

_master() {
   dot git master checkout
   git pull
   git checkout -
   dot git master merge
   git checkout -v -a
}

_module() {
   git pull
   git submodule init
   git submodule update
   git submodule status
}

cmd="$1"
shift

case $cmd in
   master|main) _master "$@" ;;
   *module) _module "$@" ;;
esac
