#!/usr/bin/env bash

source "${DOTFILES}/scripts/git/aux/core.sh"

##? Git push helpers
##?
##? Usage:
##?    push upstream <args>...
##?    push lint <args>...
##?    push commit <args>...

doc::maybe_help "$@"

_upstream() {
   local -r branch="$(git rev-parse --abbrev-ref HEAD)"
   git push -u origin "$branch"
}

_commit_first() {
   git add .
   dot git commit am "$@"
   _upstream
}

cmd="$1"
shift

case $cmd in
   commit) _commit_first "$@" ;;
   upstream) _upstream "$@" ;;
esac
