#!/usr/bin/env bash
# vim: filetype=sh

source "${DOTFILES}/scripts/core/documentation.sh"
source "${DOTFILES}/scripts/core/git.sh"

##? Git push helpers
#?? 0.1.0
##?
##? Usage:
##?    push upstream <args>...
##?    push lint <args>...
##?    push commit <args>...

docs::eval_help "$@"

_upstream() {
   local readonly branch="$(git rev-parse --abbrev-ref HEAD)"
   git push -u origin "$branch"
}

_commit_first() {
   git add . || true
   git commit -am "$1" || true
   _upstream
}

cmd="$1"
shift

case $cmd in
   commit) _commit_first "$@" ;;
   upstream) _upstream "$@" ;;
esac
