#!/usr/bin/env zsh
# vim: filetype=sh

source "${DOTFILES}/scripts/core/documentation.sh"
source "${DOTFILES}/scripts/core/git.sh"

##? Starts git ssh agent
#?? 0.1.0
##?
##? Usage:
##?    ssh

docs::eval_help "$@"

eval "$(ssh-agent -s)"
ssh-add