#!/usr/bin/env bash
# vim: filetype=sh

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/git.sh"

##? Starts git ssh agent
#?? 0.1.0
##?
##? Usage:
##?    ssh

eval "$(ssh-agent -s)"
ssh-add