#!/usr/bin/env bash
# vim: filetype=sh

source "${DOTFILES}/scripts/git/aux/core.sh"

##? Git stash viewer
##?   This script is heavily influenced by https://github.com/wfxr/git by Wenxuan Zhang
#?? 0.1.0
##?
##? Usage:
##?    stash

docs::eval_help "$@"

git::stash::show() {
   git::inside_work_tree || return 1
   local cmd opts
   cmd="git stash show \$(echo {}| cut -d: -f1) --color=always --ext-diff | $git_pager"
   opts="
   $GIT_FZF_DEFAULT_OPTS
   +s +m -0 --tiebreak=index --preview=\"$cmd\" --bind=\"enter:execute($cmd | LESS='-R' less)\"
   $GIT_STASH_FZF_OPTS
   "
    git stash list | FZF_DEFAULT_OPTS="$opts" fzf
}

git::stash::show "$@"