#!/usr/bin/env bash
# vim: filetype=sh

source "${DOTFILES}/scripts/git/aux/core.sh"

##? Git unstage (reset HEAD) selector
##?   This script is heavily influenced by https://github.com/wfxr/git by Wenxuan Zhang
#?? 0.1.0
##?
##? Usage:
##?    unstage

docs::eval_help "$@"

git::reset::head() {
   git::inside_work_tree || return 1
   local cmd files opts
   cmd="git diff --cached --color=always -- {} | $git_pager "
   opts="
   $GIT_FZF_DEFAULT_OPTS
   -m -0 --preview=\"$cmd\"
   $GIT_RESET_HEAD_FZF_OPTS
   "
    files="$(git diff --cached --name-only --relative | FZF_DEFAULT_OPTS="$opts" fzf)"
    [[ -n "$files" ]] && echo "$files" | tr '\n' '\0' | xargs -0 -I% git reset -q HEAD % && git status --short && return
    echo 'Nothing to unstage.'
}

git::reset::head "$@"