#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Desktop
#?? 0.1.0
##?
##? Usage:
##?    desktop (show|hide)
##?
##? Examples:
##?    desktop hide

docs::eval "$@"

osx::show_desktop() {
   defaults write com.apple.finder CreateDesktop -bool true
   killall Finder
}

osx::hide_desktop() {
   defaults write com.apple.finder CreateDesktop -bool false
   killall Finder
}

$show \
   && osx::show_desktop \
   || osx::hide_desktop
