#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Focus browser tab
##?
##? Usage:
##?    focus-tab <query>

doc::maybe_help "$@"

_focus_tab() {
   local -r browser="$1"
   local -r query="$2"
   local -r uri="$3"

   local code
   set +e
   read -r -d '' code <<EOF
set keystrokeDelay to 3

if application "$browser" is not running then
   do shell script "open -a Slack"
   delay keystrokeDelay
end if

set searchString to "$query"
set found to false

tell application "$browser"
    set win_List to every window
    repeat with win in win_List
        set tab_list to every tab of win
        set i to 0
        repeat with t in tab_list
            set i to i + 1
            if searchString is in (title of t as string) or searchString is in (URL of t as string) then
                set active tab index of front window to i
                activate
                return
            end if
        end repeat
    end repeat
end tell

if found is false then
   do shell script "open '$uri'"
end if

tell application "$browser"
   activate
end tell
EOF
   set -e

   osascript -e "$code"
}

_focus_app() {
   local -r browser="$1"

   osascript -e "tell application \"${browser}\" to activate"
}

main() {
   local -r browser="Vivaldi"

   _focus_tab "$browser" "$@"
}

main "$@"