#!/usr/bin/env bash
set -uo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Shows startup daemons
##?
##? Usage:
##?    startup

doc::parse "$@"

_ls() {
   log::info "$1"
   find . "$1" | awk '{print $NF}' | grep '.plist'
   echoerr
}

main() {
   _ls "/Library/LaunchDaemons"
   _ls "/System/Library/LaunchDaemons"
   _ls "/Library/LaunchAgents"
   _ls "/System/Library/LaunchAgents"
   _ls "${HOME}/Library/LaunchAgents"
}

main "$@"