#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/documentation.sh"

##? Jump to files, folders or editing
#?? 0.1.0
##?
##? Usage:
##?    jump (global|local|work|file) <args>...
##?    jump (up|root) <args>...
##?    jump edit (global|local) <editor> <args>...

docs::eval_help "$@"

   export PROMPT_COMMAND=""
   export _ZL_CD="cd"
   export _ZL_ECHO="1"
   eval "$(lua "${DOTFILES}/modules/z.lua/z.lua" --init bash)"

_fzf() {
   fzf --no-sort +m
}

fasd() {
   set +e
   _zlua "$@"
   set -e
}

_fasd_suggestions() {
   fasd -l "${@:-}" \
      | awk '{print $NF}'
}

files_for_folders() {
   for folder in $(cat); do
     find "$folder" -maxdepth 1 -type f \
       | xargs -I% echo "$folder/%"
   done
}

best_match() {
   local lines="$1"
   shift

   echo "$lines" \
      | fzf --filter="$*" \
      | head -n1
}

list_files() {
   ag --hidden --ignore .git -g "${1:-}"
}

list_folders() {
   list_files \
      | xargs -n1 dirname \
      | sort -u
}

cd_file() {
   local readonly filepath="$1"

   cd "$(dirname "$filepath")"
}

_jump() {
   local cmd="$1"
   local lines="$2"
   shift 2

   if [ $# -gt 0 ]; then
      "$cmd" "$(best_match "$lines" "$@")"
   else
      local readonly selection="$(echo "$lines" | _fzf)"
      if [ -n "$selection" ]; then
         "$cmd" "$selection"
      fi
   fi
}

jump_to_global_folder() {
   if [ $# -gt 0 ]; then
      fasd "$@"
   else
      _jump cd "$(_fasd_suggestions)"
   fi
}

jump_to_folder() {
   _jump cd "$(list_folders)"
}

jump_to_folder_for_file() {
   _jump cd_file "$(list_files)"
}

edit_global_file() {
   local readonly editor="$1"
   shift

   local readonly files="$(_fasd_suggestions "$@" | files_for_folders)"
   _jump "$editor" "$files"
}

edit_file() {
   local readonly editor="$1"
   shift

   _jump "$editor" "$(list_files)" "$@"
}

jump_to_work_folder() {
   cd "$WORK_HOME"
   _jump cd "$(ls)" "$@"
}

# Go up X directories (default: 1)
cd_up() {
   if [[ "$#" -ne 1 ]]; then
      cd ..
   else
      local d=""
      limit=$1
      for ((i=1 ; i <= limit ; i++)); do
         d="$d/.."
      done
      d="$(echo "$d" | sed 's/^\///')"
      cd "$d"
   fi
}

# Go up to project root
cd_to_git_root() {
   cd "$(git rev-parse --show-toplevel)"
}

cmd="$1"
shift

case "$cmd" in
   "local") jump_to_folder "$@" >/dev/null && pwd ;;
   "work") jump_to_work_folder "$@" >/dev/null && pwd ;;
   "file") jump_to_folder_for_file "$@" >/dev/null && pwd ;;
   "up") cd_up "$@" >/dev/null && pwd ;;
   "root") cd_to_git_root "$@" >/dev/null && pwd ;;
   "edit")
      scope="$1"
      editor="${2:-$EDITOR}"
      shift 2 || shift 1
      case "$scope" in
         "local") edit_file "$editor" "$@" ;;
         *) edit_global_file "$editor" "$@" ;;
      esac
      ;;
   *) jump_to_global_folder "$@" >/dev/null && pwd ;;
esac
