#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/git.sh"

##? Jump to files, folders or editing
##?
##? Usage:
##?    jump (global|local|work|file|dev) <args>...
##?    jump (up|root) <args>...
##?    jump edit (global|local) <editor> <args>...

doc::maybe_help "$@"

_fzf() {
   fzf --ansi --exact --no-sort +m "$@"
}

_fre_suggestions() {
   fre --sorted "${@:-}"
}

files_for_folders() {
   while IFS= read -r folder; do
      find "$folder" -maxdepth 1 -type f -print0 \
         | xargs -I% echo "$folder/%"
   done
}

best_match() {
   local lines="$1"
   shift

   echo "$lines" \
      | _fzf --filter="$*" \
      | head -n1
}

list_files() {
   ag --hidden --ignore .git -g "" # "${1:-}"
}

list_folders() {
   list_files \
      | xargs -n1 dirname \
      | sort -u
}

cd_file() {
   local -r filepath="$1"

   cd "$(dirname "$filepath")"
}

# DEPRECATED: use _select_and_apply
_jump() {
   local cmd="$1"
   local lines="$2"
   shift 2

   if [ $# -gt 0 ]; then
      "$cmd" "$(best_match "$lines" "$@")"
   else
      local -r selection="$(echo "$lines" | _fzf)"
      if [ -n "$selection" ]; then
         "$cmd" "$selection"
      fi
   fi
}

_select_and_apply() {
   local cmd="$1"
   shift 1

   if [ $# -gt 0 ]; then
      "$cmd" "$(best_match "$(cat)" "$@")"
   else
      local -r selection="$(_fzf)"
      if [ -n "$selection" ]; then
         "$cmd" "$selection"
      fi
   fi
}

jump_to_global_folder() {
   _jump cd "$(_fre_suggestions)" "$@"
}

jump_to_folder() {
   _jump cd "$(list_folders)"
}

jump_to_folder_for_file() {
   _jump cd_file "$(list_files)"
}

edit_global_file() {
   local -r editor="$1"
   shift

   local -r files="$(_fre_suggestions "$@" | files_for_folders)"
   _jump "$editor" "$files"
}

edit_file() {
   local -r editor="$1"
   shift

   _jump "$editor" "$(list_files)" "$@"
}

jump_to_specific_folder() {
   local -r folder="$1"
   shift

   cd "$folder"
   FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --exact --preview 'cd {} && lsd . --color always'" _jump cd "$(ls)" "$@"
}

jump_to_work_folder() {
   cd "$DEV_HOME"

   local -r GO_DIR="${DEV_HOME}/go/src/code.uber.internal"

   _go_projs() {
      cd "$GO_DIR"
      find . -mindepth 2 -maxdepth 2 -type d | cut -c 3-
   }

   _work_home_projs() {
      cd "$WORK_HOME"
      find . -maxdepth 3 -not -path "./go-code/*" -type d -name .git -prune | cut -c 3- | sed 's|/.git$||'
   }

   _suffix() {
      awk -v suffix="$1" -v color="$2" '{printf("%s%sm%-32s%s\n", NC "\033[0;", color, $1, suffix) }'
   }

   _cd() {
      local -r input="$(echo "$1" | xargs)"
      local -r dir="$(echo "$input" | cut -d' ' -f1)"
      local -r kind="$(echo "$input" | cut -d' ' -f2)"

      case "$kind" in
         "dev/go") realpath "${GO_DIR}/${dir}" ;;
         *) realpath "${WORK_HOME}/${dir}" ;;
      esac
   }

   (_go_projs | _suffix 'dev/go' 32; _work_home_projs | _suffix 'dev/uber' 34) \
      | _select_and_apply _cd "$@"
}

jump_to_uber_go() {
   _jump cd "$projects" "$@"
}

# Go up X directories (default: 1)
cd_up() {
   if [[ "$#" -ne 1 ]]; then
      cd ..
   else
      local d=""
      limit=$1
      for ((i=1 ; i <= limit ; i++)); do
         d="$d/.."
      done
      d="$(echo "$d" | sed 's/^\///')"
      cd "$d"
   fi
}

# Go up to project root
cd_to_git_root() {
   cd "$(git::root)"
}

cmd="$1"
shift

case "$cmd" in
   "local") jump_to_folder "$@" >/dev/null && pwd ;;
   "work") jump_to_work_folder "$@" ;;
   "dev") jump_to_specific_folder "$DEV_HOME" "$@" >/dev/null && pwd ;;
   "file") jump_to_folder_for_file "$@" >/dev/null && pwd ;;
   "up") cd_up "$@" >/dev/null && pwd ;;
   "root") cd_to_git_root "$@" >/dev/null && pwd ;;
   "edit")
      scope="$1"
      editor="${2:-$EDITOR}"
      shift 2 || shift 1
      case "$scope" in
         "local") edit_file "$editor" "$@" ;;
         *) edit_global_file "$editor" "$@" ;;
      esac
      ;;
   *) jump_to_global_folder "$@" >/dev/null && pwd ;;
esac
