#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/nav.sh"

##? JSON navigator
##?
##? Usage:
##?    nav [<path>]

docs::eval_help "$@"

path::all() {
   echo "TODO"
}

path::is_navigable() {
   local -r path="$1"
   fs::is_dir "$path"
}

_ls() {
   lsd --color always -A "$@" || ls -A "$@"
}

nav::ls() {
   local -r path="${1:-$CWD}"
   _ls "$path" \
      | grep -v '.DS_Store'
}

action::view() {
   local -r path="$1"
   if fs::is_dir "$path"; then
      nav::ls "$path" \
         | less -R
   else
      dot shell less "$path" \
         | less -R
   fi
}

path::start() {
   pwd
}

fzf::extra_bindings() {
   echo "ctrl-e:execute($0 --action edit --cwd $CWD --path {})"
   echo "ctrl-o:execute($0 --action fm --cwd $CWD --path {})+abort"
}

action::edit() {
   "$EDITOR" "$1"
}

action::fm() {
   cd "$CWD"
   vifm "."
}

action::before_exit() {
   echo "$CWD"
}

action::handle_extra() {
   case $action in
      edit) action::edit "$(path::resolve "$path")" < /dev/tty > /dev/tty ;;
      fm) action::fm < /dev/tty > /dev/tty ;;
      *) action::abort "$@" ;;
   esac
}

# ===============
# main
# ===============

input::parse "$@"
nav::cd "$CWD"
action::handle
