#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Filesystem info
#?? 0.1.0
##?
##? Usage:
##?    size [<path>]
##?
##? Examples:
##?    size                Total size of current directory
##?    size somepath       Size of a file or directory

docs::eval_help "$@"

if du -b /dev/null >/dev/null 2>&1; then
   arg=-sbh
else
   arg=-sh
fi
shift
if [[ -n "$@" ]]; then
   du $arg -- "$@"
else
   du $arg .[^.]* ./*
fi
