#!/usr/bin/env bash

FIRST_CHARACTER_OK="♪"
FIRST_CHARACTER_KO="$FIRST_CHARACTER_OK"
PROMPT_COLOR_0="{cyan}"
PROMPT_COLOR_1="{green}"
AHEAD="⇣"
BEHIND="⇡"
DIVERGED="⥄"
DIRTY="✗"
NONE="✓"

prompt_dns_pwd() {
   prompt_dir="${PWD/$HOME/\~}"
   print -n "%F${PROMPT_COLOR_0}${prompt_dir}"$'\n'
}

prompt_dns_git() {
   [[ -n ${git_info} ]] && print -n "${(e)git_info[prompt]}"
}

prompt_dns_precmd() {
   (( ${+functions[git-info]} )) && git-info
}

prompt_dns_setup() {
   local prompt_dns_status="%(?:%F${PROMPT_COLOR_1}$FIRST_CHARACTER_OK:%F{red}$FIRST_CHARACTER_KO)%F{reset}"

   autoload -Uz add-zsh-hook && add-zsh-hook precmd prompt_dns_precmd

   prompt_opts=(cr percent sp subst)

   zstyle ':zim:git-info:branch' format "%F${PROMPT_COLOR_1}%b"
   zstyle ':zim:git-info:commit' format '%c'

   if ! ${DOT_PREVENT_DIRTY:-true}; then
      zstyle ':zim:git-info:clean' format '%F{white}$NONE'
      zstyle ':zim:git-info:dirty' format '%F{yellow}$DIRTY'
   else
      zstyle ':zim:git-info:clean' format ''
      zstyle ':zim:git-info:dirty' format ''
   fi

   zstyle ':zim:git-info:keys' format 'prompt' ' %F{cyan}%b%c %C%D'

   PS1=$'\n'"\$(prompt_dns_pwd)\$(prompt_dns_git)%f"$'\n'"${prompt_dns_status} "
   RPS1=''
}

prompt_dns_setup "${@}"
