[character]
symbol = "♪"

[git_state]
disabled = true

[git_status]
disabled = true

[aws]
disabled = true
symbol = " "

[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
disabled = true
symbol = " "

[dart]
disabled = true
symbol = " "

[docker]
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[git_branch]
symbol = " "

[golang]
disabled = true
symbol = " "

[haskell]
disabled = true
symbol = " "

[hg_branch]
disabled = true
symbol = " "

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = " "

[nim]
disabled = true
symbol = " "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = " "

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[python]
disabled = true
symbol = " "

[ruby]
disabled = true
symbol = " "

[rust]
disabled = true
symbol = " "

[swift]
disabled = true
symbol = "ﯣ "
