#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)"
export DOTFILES="${DOTFILES:-$ROOT_DIR}"
source "${DOTFILES}/tests/core.sh"

res="$(dot::call env health)"

test::case "dot <ctx> <cmd> works"

echo "$res" | grep "====" \
   && test::success || test::fail
