#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)"
export DOTFILES="${DOTFILES:-$ROOT_DIR}"
source "${DOTFILES}/tests/core.sh"

_output() {
   echo no | "$DOT_PATH" -d "environment" "init"
}

test::fact "scripts/environment/init starts"

echo "$(_output)" \
   | grep risk \
   && test::success || test::fail
