#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)"
export DOTFILES="${DOTFILES:-$ROOT_DIR}"
source "${DOTFILES}/scripts/core/main.sh"

_install_jq() {
  brew install jq || apk add jq || apt install jq
}

log::warning "Test case: all JSONs are syntactically valid"

cd "$DOTFILES"

platform::command_exists jq \
  || _install_jq

find . -iname "*.json" \
  | grep -Ev 'node_modules|cache|modules/|lock.json' \
  | xargs jq .
