#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)"
export DOTFILES="${DOTFILES:-$ROOT_DIR}"
source "${DOTFILES}/tests/core.sh"

test::fact "all JSONs are syntactically valid"

cd "$DOTFILES"

find . -iname "*.json" \
   | grep -Ev 'node_modules|cache|modules/|lock.json' \
   | xargs -I% "$DOT_PATH" -d code parser json % \
   && test::success || test::fail
