#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? IGDB
##?
##? Usage:
##?    igdb [<query>]

doc::parse "$@"

sample_query() {
   echo 'fields name;
      search "Sonic the Hedgehog";
      where platforms = (29);
      limit 5;'
}

main() {
   local -r query="${1:-"$(sample_query)"}"

   curl -X POST \
      'https://api.igdb.com/v4/games' \
      --header 'Accept: */*' \
      --header 'User-Agent: Thunder Client' \
      --header "Client-ID: $(dot security store get igdb/client_id)" \
      --header "Authorization: Bearer $(dot security store get igdb/token)" \
      --header 'Content-Type: text/plain' \
      --data-raw "$query"
}

main "$query" | jq