#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? ROM helpers
##?
##? Usage:
##?    rom rename
##?    rom emuparadise list <url>
##?
##? Examples:
##?    rom rename
##?    rom emuparadise list https://www.emuparadise.me/Super_Nintendo_Entertainment_System_(SNES)_ROMs/List-All-Titles/5

doc::parse "$@"

_rename_rom() {
   tr '_' ' ' \
      | sed -E 's/ (ROM|ISO) *$//g' `# remove download suffixes` \
      | sed -E 's/\([^\)]+\)//g' `# remove (...)` \
      | sed -E 's/\[[^\]+\]//g' `# remove [...]` \
      | sed -E 's/^[0-9]+ \- //g' `# remove 1234 -`  \
      | sed -E 's/Decrypted *//g' \
      | sed 's/Bros./Bros/g' \
      | sed 's/Pokemon/Pokémon/g' \
      | sed 's/Legend of Zelda, The/The Legend of Zelda/g' \
      | sed -E 's/v[0-9\.]+//g' `# remove v1.2` \
      | sed -E 's/(.*), ?The *$/The \1/g' `# remove , The from the ending` \
      | sed 's/^ *//;s/ *$//' `# left and right trim` \
      | sed -E 's/  */ /g' `# remove consecutive spaces` \
      | sed -E 's/ *\.0/\.0/g' `# fix SNES saves`
}

_rename_ext() {
   tr '[:upper:]' '[:lower:]'
}

_rename_dir() {
   cat
}

_quoted() {
   sed 's/^/"/g' | sed 's/$/"/g'
}

_rename() {
   local -r input="$(cat)"

   local -r splits="$(echo "$input" | sed -E 's|([^/]+)\.([^\.]+)$|;\1;\2|g')"
   local -r new_dirs="$(echo "$splits" | cut -f1 -d';' | _rename_dir)"
   local -r new_roms="$(echo "$splits" | cut -f2 -d';' | _rename_rom)"
   local -r new_exts="$(echo "$splits" | cut -f3 -d';' | _rename_ext)"

   # shellcheck disable=SC2001
   local -r output="$(paste <(echo "$new_dirs") <(echo "$new_roms") <(echo "$new_exts" | sed 's/^/\./g') | tr -d '\t')"

   paste <(echo "$input" | _quoted) <(echo "$output" | _quoted) \
      | sed 's/^/mv /g' \
      | sed -E 's|"[ \s\t]+"|" "|g'
}

if $rename; then
   _rename
elif $emuparadise && $list; then
   curl "$url" \
      | grep -Eo 'class="index gamelist" title="([^"]+)' \
      | cut -c 31-
fi
