#!/usr/bin/env bash

source "${DOTFILES}/scripts/kafka/aux/core.sh"

case $1 in
   "consumer") bin="kafka-console-consumer" ;;
   "producer") bin="kafka-console-producer" ;;
   *) kafka::invalid "$@" ;;
esac

kafka::call "$bin" "$@"
