#!/usr/bin/env bash

source "${DOTFILES}/scripts/kafka/aux/core.sh"

case $1 in
   "start")
      bin="kafka-server-start"
      if [ "$#" -eq 1 ]; then
         arg="$KAFKA_HOME/config/server.properties";
      fi
      ;;
   "stop") bin="kafka-server-stop" ;;
   *) kafka::invalid "$@" ;;
esac

kafka::call "$bin" "$@" "$arg"

