#!/usr/bin/env bash
set -euo pipefail

export DOTFILES="${DOTFILES:-"$HOME/.dotfiles"}"
source "$DOTFILES/git/core.sh"

git_dir=$(git rev-parse --show-toplevel)
files=$(git diff-index --name-only --diff-filter=ACM --cached HEAD --)

git::check_json "$files"
git::check_edn "$files"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against="HEAD"
else
	against=$(git hash-object -t tree /dev/null)
fi

git_diff=$(git diff --cached --name-only "$against")
existing_diff="$(echo "$git_diff" | perl -ne 'chomp(); if (-e $_) {print "$_\n"}')"

# git::check_aws "$existing_diff"
git::check_conflict "$existing_diff"
git::match_filename "$existing_diff" ".*secret.*" true
git::match_content "$existing_diff" "code debug" "nu/tap" false
