#!/usr/bin/env bash
set -euo pipefail

source "$DOTFILES/scripts/core/main.sh"

function main() {
	local current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
	prompt_if_protected "$current_branch" "tmp"
}

function prompt_if_protected() {
	local current_branch="$1"
	local protected_branch="$2"
	if [ $protected_branch = $current_branch ]; then  
	    if ! prompt_confirmation "Are you sure you want to push to $protected_branch?" true; then
	    	exit 1
	    fi
	fi  
}

main
exit 0