#!/usr/bin/env bash
set -euo pipefail

source "$DOTFILES/scripts/core/main.sh"

function prompt_if_master() {
	local protected_branch='master'  
	if [ $protected_branch = $current_branch ]; then  
	    read -p "Are you sure you want to push to master? (y|n) " -n 1 -r < /dev/tty
	    echo
	    if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
	        exit 0 
	    fi
	    exit 1 
	else  
	    exit 0 
	fi  
}

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

prompt_if_master "$current_branch"
