#!/usr/bin/env zsh

#compdef dot

_command_for() {
   command ls "${DOTFILES}/scripts/${1:-}" | grep -v / | xargs echo
}

_dot() {
   local curcontext="$curcontext" state line
   typeset -A opt_args

   _arguments \
      '1: :->context' \
      '2: :->command' \
      '*: :->args'

   case $state in
      context)
         existing_contexts="$(_command_for)"
         _arguments "1:Context:($existing_contexts)"
         ;;
      command)
         existing_commands=$(_command_for $words[2])
         _arguments "2:Command:($existing_commands)"
         ;;
      *)
         _files
         ;;
   esac
}

_dot "$@"
