#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/pkg/aux/batch.sh"

##? Install multiple dependencies
##?
##? Usage:
##?    batch <name>

name="$1"
deps="$(batch::dependencies "$name" | str::join)"
dot pkg add "${deps[@]}"
