# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2

job_defaults: &defaults
    docker:
      - image: frolvlad/alpine-bash
    working_directory: ~/repo
    environment:
      ENVIRONMENT: "test"
      TERM: "dumb"

jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: apk add git
      - run: 
          command: ./bin/dot self test

workflows:
  version: 2
  run-tests:
    jobs:
      - tests
