# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2

job_defaults: &defaults
    docker:
      - image: frolvlad/alpine-bash
    working_directory: ~/repo
    environment:
      ENVIRONMENT: "test"

jobs:
  test:
    <<: *defaults
    # Download and cache dependencies
    steps:
      - checkout
      - run:
          name: Dot
          command: ./tests/dot
      - run:
          name: Symlinks
          command: ./tests/symlinks
      - run:
          name: JSON
          command: ./tests/json

workflows:
  version: 2
  run-tests:
    jobs:
      - test
