#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/log.sh"

##? Decrypts content
##?
##? Usage:
##?    decrypt [options]
##?
##? Options:
##?    -a --algorithm <algo>   decryption algorithm [default: 256]
##?    -p --pass <pass>        Password
##?
##? Examples:
##?    echo U2FsdG= | decrypt "foo bar"
##?    echo U2FsdG= | decrypt "foo bar" -a 0
##?    echo U2FsdG= | decrypt "foo bar" -a 256 -p swordfish

doc::parse "$@"

algo_0() {
   log::err "Impossible to decrypt"
   exit 1
}

algo_1() {
   log::err "Impossible to decrypt"
   exit 1
}

algo_256() {
   local -r content="$1"
   local -r pass="$2"

   echo "$content" | openssl enc -aes256 -a -d -k "$pass"
}

content="$(cat)"

case "$algorithm" in
   0)
      algo_0 "$content"
      ;;
   1)
      algo_1 "$content"
      ;;
   256)
      algo_256 "$content" "$pass"
      ;;
   *)
      echo "Invalid algorithm"
      exit 1
      ;;
esac
