#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Encrypts content
##?
##? Usage:
##?    encrypt [options]
##?
##? Options:
##?    -a --algorithm <algo>   Encryption algorithm [default: 256]
##?    -p --pass <pass>        Password
##?
##? Examples:
##?    echo 123 | encrypt "foo bar"
##?    echo 123 | encrypt "foo bar" -a 0
##?    echo 123 | encrypt "foo bar" -a 256 -p swordfish

docs::eval "$@"

md5_fn() {
   if platform::command_exists md5sum; then
      echo "$1" | md5sum
   elif platform::command_exists md5; then
      echo "$1" | md5
   else
      echo "No md5 algorithm available"
      exit 2
   fi
}

algo_0() {
   md5_fn "$1" | base64 | cut -c -16
}

algo_1() {
   md5_fn "$1"
}

algo_256() {
   local -r content="$1"
   local -r pass="$2"

   echo "$content" | openssl enc -aes256 -a -k "$pass"
}

content="$(cat)"

case "$algorithm" in
   0)
      algo_0 "$content"
      ;;
   1)
      algo_1 "$content"
      ;;
   256)
      algo_256 "$content" "${pass:-}"
      ;;
   *)
      echo "Invalid algorithm"
      exit 1
      ;;
esac
