#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Calculates sha256
##?
##? Usage:
##?    sha256 [<args>...]
##?
##? Examples:
##?    echo 123 | sha256

doc::maybe_help "$@"

sha256() {
   if has sha256sum; then
      sha256sum "$@"
   elif has shasum; then
      shasum -a 256 "$@"
   elif has openssl; then
      openssl dgst -sha256 "$@"
   else
      echoerr "Unable to calculate sha256!"
      exit 43
   fi
}

sha256 "$@"