#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/download/core.sh"

##? Download file name parser
 #? 0.1.0
##?
##? Usage:
##?    move

docs::eval "$@"

_video_content() {
  local readonly f="$(cat)"
  local readonly first_call="${1:-true}"
  if fs::is_dir "$f" && ! $first_call; then
    ls "$f" | _video_content false
  else
    echo "$f" | grep -Eiq '\.(avi|mp4|mov|mkv|mpg)$'
  fi
}

_move_video() {
  local readonly filename="$(cat)"
  for t in $HOME/TV\ Shows/*; do
    echo "$filename $(basename "$t") $(str::levenshtein "$(basename "$t")" "$filename")"
  done
}


for f in ./*.mov; do
  echo "$f - $(echo "$f" | _video_content | _move_video || true)"
done
