#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/download/aux/core.sh"

##? Download file name parser
#?? 0.1.0
##?
##? Usage:
##?    move

docs::eval "$@"

DOWNLOADS_FOLDER="$HOME/Downloads/test"
TV_FOLDER="$HOME/TV"
MOVIES_FOLDER="$HOME/Movies"

_video_content() {
   local readonly f="$(cat)"
   local readonly first_call="${1:-true}"
   if fs::is_dir "$f" && ! $first_call; then
      ls "$f" | _video_content false
   else
      echo "$f" | grep -Eiq "\.${VIDEO_EXTENSIONS}$"
   fi
}

_tv_folder() {
   local readonly filename="$(dot down parser video name "$full_filename")"
   local dist
   cd "$TV_FOLDER"
   for t in *; do
      dist=$(str::filename_levenshtein "$t" "$filename")
      if [ "$dist" -lt 5 ]; then
         basename "$t"
         exit 0
      fi
      echo "$filename"
   done
}

_move_video() {
   local readonly full_filename="$1"
   local readonly info="$(dot down parser video "$full_filename")"
   local readonly is_tv="$(echo "$info" | grep tv | awk '{print $2}')"
   local readonly filename="$(echo "$info" | grep reduced | gsed -E 's/.*?\[0m\s(.*)/\1/')"
   if $is_tv; then
      local readonly folder="$(_tv_folder "$filename")"
      echo "mv \"${DOWNLOADS_FOLDER}/${full_filename}\" \"${TV_FOLDER}/${folder}\""
   else
      echo "mv \"${DOWNLOADS_FOLDER}/${full_filename}\" \"${MOVIES_FOLDER}/${filename}\""
   fi
}

pushd "$DOWNLOADS_FOLDER" >/dev/null

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for f in ./*; do
   is_video=$(echo "$f" | _video_content && echo true || echo false)
   if $is_video; then
      _move_video "${f:2}"
   fi
done

IFS=$SAVEIFS

popd >/dev/null
