#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/download/core.sh"

##? Download file name parser
 #? 0.1.0
##?
##? Usage:
##?    move

docs::eval "$@"

TV_FOLDER="$HOME/TV"

_video_content() {
  local readonly f="$(cat)"
  local readonly first_call="${1:-true}"
  if fs::is_dir "$f" && ! $first_call; then
    ls "$f" | _video_content false
  else
    echo "$f" | grep -Eiq "\.${VIDEO_EXTENSIONS}$"
  fi
}

_tv_folder() {
  local readonly filename="$(dot down parser video name "$full_filename")"
  local dist
  for t in $TV_FOLDER/*; do
    dist=$(str::filename_levenshtein "$t" "$filename")
    if [ "$dist" -lt 5 ]; then
      basename "$t"
      exit 0
    fi
    echo "$filename"
  done
}

_move_video() {
  local readonly full_filename="$1";
  local readonly filename="$(dot down parser video name "$full_filename")"
  local readonly folder="$(_tv_folder "$filename")"
  echo "mv $full_filename $folder"
}

for f in ./*; do
  is_video=$(echo "$f" | _video_content && echo true || echo false)
  if $is_video; then
    _move_video "${f:2}"
  fi
done
