#!/usr/bin/env bash
# shellcheck disable=SC2004,SC2015,SC2155,SC2206,SC2016,SC2220,SC2162,SC2155
set -eo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Simulates typing
##?
##? Usage:
##?    type <text> <speed>
##?
##? Examples:
##?    type 'foo bar' 100

doc::maybe_help "$@"

main() {
   local text="$1"
   local speed="${2:-10}"
   local wait=$(echo "scale=2; 1 / ${speed}" | bc)

   while read -r -n1 character; do
      count="$(echo "$character" | wc -w | xargs)"
      if [[ $count -gt 0 ]]; then
         printf '%s' "$character"
      else
         printf ' '
      fi
      sleep "$wait"
   done < <(echo -n "$text")
   echo
}

main "$@"