#!/usr/bin/env bash
set -eo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Simulates typing
##?
##? Usage:
##?    type <text> <speed>
##?
##? Examples:
##?    type 'foo bar' 100

docs::eval_help "$@"

text="$1"
speed="${2:-10}"
wait=$(echo "scale=2; 1 / ${speed}" | bc)

while read -n1 character; do
   count="$(echo "$character" | wc -w | xargs)"
   if [[ $count > 0 ]]; then
      printf "$character"
   else
      printf ' '
   fi
   sleep "$wait"
done < <(echo -n "$text")
echo