#!/usr/bin/env bash
set -euo pipefail

source $DOTFILES/scripts/core/main.sh 

##? Native alert
 #? 0.1.0
##?
##? Usage:
##?    alert <title> <message>
##?    alert <title> <subtitle> <message>
##?
##? Examples:
##?    alert title message

docopts "$@"

if [ -n $message ]; then
	[ -n $subtitle ] \
		&& osascript -e "display notification \"$message\" with title \"$title\" subtitle \"$subtitle\"" \
		|| osascript -e "display notification \"$message\" with title \"$title\""
fi

