#!/usr/bin/env bash
set -euo pipefail

source $DOTFILES/scripts/core/main.sh 

##? Pushbullet API
 #? 0.1.0
##?
##? Usage:
##?    push list
##?    push <device> note <title> [<message>]
##?    push <device> link <url> 
##?    push <device> link <title> <url>
##?    push <device> link <title> <message> <url>
##?    push -- <args>...
##?
##? Examples:
##?    push list
##?    push -- list
##?    push moto note title message
##?    push moto link http://google.com
##?    push moto link title message http://google.com

docopts "$@"

PUSH_DIR="${DOTFILES}/modules/pushbullet"
PUSH_BIN="${PUSH_DIR}/pushbullet"

function clone_cli() {
	mkdir -p "$PUSH_DIR"
	git clone https://github.com/Red5d/pushbullet-bash.git "$PUSH_DIR"
	cd "$PUSH_DIR"
	git submodule init && git submodule status && git submodule update --init --recursive "${PUSH_DIR}" || true
}

# clone repository if needed
if ! is_file "$PUSH_BIN"; then
	clone_cli
fi

# adapt input
if $note || $link; then
	args=("push" "${@:-}")
else
	args="${@:-}"
fi

# call cli
bash "$PUSH_BIN" "${args[@]:-}"
