#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Pushbullet API
#?? 0.1.0
##?
##? Usage:
##?    push list
##?    push <device> note <title> [<message>]
##?    push <device> link <url>
##?    push <device> link <title> [<message>] <url>
##?    push -- <args>...
##?
##? Examples:
##?    push list
##?    push -- list
##?    push moto note title message
##?    push moto link http://google.com
##?    push moto link title message http://google.com

docs::eval "$@"

PUSHBULLET_HOME="${PUSHBULLET_HOME:-${DOTFILES}/modules/pushbullet-bash}"

best_match() {
  "$0" list \
    | fzf --filter="$*" \
    | head -n1
}

# clone repository if needed
dot pkg add pushbullet-bash &> /dev/null

# adapt input
if $note || $link; then
   device="$(best_match "$1")"
   shift
   args=("push" "$device" "${@:-}")
else
   args="${@:-}"
fi

# call cli
cd "$PUSHBULLET_HOME"

bash ./pushbullet "${args[@]:-}"
