#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/log.sh"

##? Pushbullet API
##?
##? Usage:
##?    push [options] list
##?    push [options] note <title> [<message>]
##?    push [options] url <uri>
##?    push [options] url <title> [<message>] <uri>
##?    push [options] auth
##?    push [options] app <name>
##?    push [options] shot
##?    push [options] write <text>
##?    push [options] say <text>
##?    push [options] share <text>
##?    push [options] raw <args>...
##?
##? Options:
##?    -d --device <device>     Device to push [default: phone]
##?
##? Examples:
##?    push list
##?    push note sometext
##?    push url http://google.com
##?    push app Gmail --device tablet

doc::parse "$@"

PUSHBULLET_HOME="${PUSHBULLET_HOME:-${DOTFILES}/modules/pushbullet-bash}"

if [ -z "${PUSHBULLET_API_KEY:-}" ]; then
   die "Please set \$PUSHBULLET_API_KEY first"
fi

best_match() {
   "$0" list \
      | fzf --filter="$*" \
      | head -n1
}

build_msg() {
   local -r type="$1"
   local -r txt="${2:-null}"
   echo "${type};${txt}"
}

call_api() {
   cd "$PUSHBULLET_HOME"
   PB_API_KEY="$PUSHBULLET_API_KEY" bash ./pushbullet "${@:-}"
}

# call cli with raw args
if [[ ${#args[@]} -gt 0 ]]; then
   call_api "${args[@]:-}"
   exit 0
fi

if ! $list && [ -n "${device:-}" ]; then
   case "$device" in
      moto|g4) device="Moto G4 Plus" ;;
      phone|xiaomi|mi|9t|pro) device="Xiaomi Mi 9T Pro" ;;
      tablet|tab|galaxy|samsung) device="Galaxy Tab A" ;;
      all|broadcast) device="all" ;;
      chrome|pc|desktop|mac|windows|computer|win|osx|linux|notebook) device="Chrome" ;;
      *) device="$(best_match "$device")" ;;
   esac
fi

if $list; then
   args=("list")
elif $url; then
   args=("push" "$device" "link")
   [ -n "${title:-}" ] && args+=("$title")
   [ -n "${message:-}" ] && args+=("$message")
   [ -n "${uri:-}" ] && args+=("$uri")
else
   args=("push" "$device" "note")
   if $note; then
      [ -n "${title:-}" ] && args+=("$title")
      [ -n "${message:-}" ] && args+=("$message")
   elif $app; then
      args+=("$(build_msg app "$name")")
   elif $shot; then
      args+=("$(build_msg shot)")
   elif $auth; then
      args+=("$(build_msg auth)")
   elif $write; then
      args+=("$(build_msg write "$text")")
   elif $say; then
      args+=("$(build_msg say "$text")")
   elif $share; then
      args+=("$(build_msg share "$text")")
   fi
fi

# clone repository if needed
dot pkg add pushbullet-bash &> /dev/null

# call cli
if ! $list; then
   log::warn "${args[@]:-}"
fi
call_api "${args[@]:-}"
