#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Gets cover for books
##?
##? Usage:
##?    cover [options] <query>
##?
##? Options:
##?    -d --display       Show image instead of printing the URL
##?    -z --zoom <zoom>   Zoom level [default: 0]

docs::eval "$@"

get_json() {
  local readonly query="$(str::urlencode "$1")"

  curl -s \
    "https://www.googleapis.com/books/v1/volumes?q=$query" \
    -H 'Accept: application/json, text/javascript, */*; q=0.01' \
    -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36' \
    -H 'DNT: 1'
}

thumbnail() {
  jq -r '.items | first | .volumeInfo.imageLinks.thumbnail'
}

big() {
  sed "s/oom=1/oom=${zoom}/g"
}

url="$(get_json "$query" | thumbnail | big)"

if $display; then
  wget -qO- "$url" | imgcat
else
  echo "$url"
fi


