#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/envoy/aux/core.sh"

##? Run linters and formatters
##?
##? Usage:
##?    fix

doc::maybe_help "$@"

_fix() {
    platform::validate_remote
    
    log::info "Running fixers..."
    cd "$REMOTE_ENVOY_MUTABLE"
    ./tools/code_format/check_format.py fix || true
    ./tools/proto_format/proto_format.sh fix || true
    ./tools/proto_format/proto_sync.py || true
}

main() {
    local -r fn="$1"
    shift || true
    "_${fn}" "$@"
}

main "$@"
