#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/envoy/aux/core.sh"

##? Setup dev machine
##?
##? Usage:
##?    init

doc::maybe_help "$@"

_profile() {
    echo
    echo 'source "${HOME}/.bashrc"'
}

main() {
    EDITOR=echo \
        DOT_ZIM=false \
        DOT_THEME="none" \
        DOT_LINK_EXTRA_ARG="--backup" \
        DOT_SKIP_PM_UPDATE=true \
        DOT_SKIP_CORE_DEPS=true \
        DOT_SKIP_UPDATE=true \
        DOT_ZSHRC_EXTRA='source "${DOTFILES}/scripts/envoy/aux/bash.rc"' \
        dot self update

    dot pkg add git bash rsync bazel curl wget protoc pipenv fzf gitui 

    _profile >> "${HOME}/.profile" 
}

main "$@"
