#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/envoy/aux/core.sh"

##? ssh into dev machine
##?
##? Usage:
##?    ssh

doc::maybe_help "$@"

main() {
   platform::validate_local

   kitty +kitten ssh "${USER}@${IP}"
}

main "$@"
