#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/envoy/aux/core.sh"

##? ssh into dev machine
##?
##? Usage:
##?    ssh

doc::maybe_help "$@"

_ssh() {
   log::info "$@"
   ssh "$@"
}

main() {
   platform::validate_local

   _ssh "${USER}@${IP}"
}

main "$@"
