#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/knowledge/aux/core.sh"

##? Open knowledge's UI
##?
##? Usage:
##?    ui

doc::maybe_help "$@"

cd "${KNOWLEDGE_HOME}"
yarn run build