#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/knowledge/aux/core.sh"

##? Open knowledge's UI
##?
##? Usage:
##?    ui

doc::maybe_help "$@"

cd "${KNOWLEDGE_HOME}/build"
python3 -m http.server 8123 &
dot system open -b "http://localhost:8123"