#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/ini.sh"

##? Bookmarks
##?
##? Usage:
##?    mark <args>...
##?
##? Examples:
##?    mark mail

doc::maybe_help "$@"

_url() {
   cat "${DOTFILES}/local/marks.ini" | ini::get "$*"
}

action=(dot system open)

for u in $(_url "$*"); do
   "${action[@]}" "$u"
done
