#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/torrent/aux/core.sh"

##? Download file name parser
#?? 0.1.0
##?
##? Usage:
##?    parser video [name] <filename>

docs::eval "$@"

_remove_match() {
   local -r match="${1:-}"
   cat | sed "s/${match}//g"
}

_apply_field_hack() {
   local -r field="${1:-}"
   local -r content="$(cat)"
   if [ -z "$content" ]; then
      echo "$content"
   else
      case $field in
         season) echo "${content:0:-1}" ;;
         episode) echo "${content:0:-1}" ;;
         *) echo "$content" ;;
      esac
   fi
}

_apply_reduced_hacks() {
   local -r filename="${1:-}"
   echo "$filename" | sed 's/\./ /g' | xargs
}

_append() {
   echo "${1}${CYAN}${2}${NC} ${3}\n"
}

_remove_blank_lines() {
   cat | sed 's/^ *//; s/ *$//; /^$/d; /^\s*$/d'
}

declare -A regexes
regexes=(
   ["episode"]="(s?([0-9]{1,2}))([ex]([0-9]{2})(?:[^0-9]|$))"
   ["extension"]="\.(${VIDEO_EXTENSIONS})$"
   ["year"]="([\[\(]?((?:19[0-9]|20[01])[0-9])[\]\)]?)"
   ["resolution"]="([0-9]{3,4}p)"
   ["codec"]="(xvid|[hx]\.?26[45])"
   ["group"]="(- ?([^-]+(?:-={[^-]+-?$)?))$"
   ["region"]="R[0-9]"
   ["extended"]="(EXTENDED(:?.CUT)?)"
   ["hardcoded"]="HC"
   ["proper"]="PROPER"
   ["repack"]="REPACK"
   ["container"]="(${VIDEO_EXTENSIONS})"
   ["widescreen"]="WS"
   ["website"]="^(\[ ?([^\]]+?) ?\])"
   ["language"]="(russian|english|pt-br|portug|english|spanish)"
   ["sbs"]="(?:Half-)?SBS"
   ["unrated"]="UNRATED"
   ["quality"]="((?:PPV\.)?[HP]DTV|(?:HD)?CAM|B[DR]Rip|(?:HD-?)?TS|(?:PPV )?WEB-?DL(?: DVDRip)?|HDRip|DVDRip|DVDRIP|CamRip|W[EB]BRip|BluRay|DvDScr|hdtv|telesync)"
   ["sub"]="(sub)"
   ["audio"]="(MP3|DD5\.?1|Dual[\- ]Audio|LiNE|DTS|AAC[.-]LC|AAC(?:\.?2\.0)?|'AC3(?:\.5\.1)?)"
   ["size"]="(\d+(?:\.\d+)?(?:GB|MB))"
)

declare -a orders=("episode" "extension" "year" "resolution" "codec" "group" "region" "extended" "hardcoded" "proper" "repack" "container" "widescreen" "website" "language" "sbs" "unrated" "quality" "sub" "audio" "size")

reduced_filename="$filename"
output=""

CYAN='\033[0;36m'
NC='\033[0m'

for field in "${orders[@]}"; do
   match="$(echo "$reduced_filename" | grep -iPo "${regexes[$field]}" | _apply_field_hack "$field" || echo "")"
   if [ -n "$match" ]; then
      output="$(_append "$output" "$field" "$match")"
      reduced_filename=$(echo "$reduced_filename" | _remove_match "$match")
   fi
done

is_tv="$(echo "$output" | grep -Eq 'season|episode' && echo "true" || echo "false")"
output="$(_append "$output" "tv" "$is_tv")"

reduced_filename="$(_apply_reduced_hacks "$reduced_filename")"
output="$(echo "$(_append "$output" "reduced" "$reduced_filename")" | sed -E 's/\\n$//')"

if $name; then
   echo "$reduced_filename" | _remove_blank_lines
else
   echo -e "$output" | _remove_blank_lines
fi
