#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Open WhatsApp page
##?
##? Usage:
##?    whatsapp <number>
##?
##? Examples:
##?    whatsapp 5511999999999

doc::maybe_help "$@"

_launch() {
   dot script open -b "https://web.whatsapp.com/send?phone=$*&text&app_absent=1"
}

main() {
   local number
   number="${1//[^0-9]/}"
   if [[ ${#number} -lt 12 ]]; then
      number="5511${number}"
   fi
   _launch "$number"
}

main "$@"
