#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Open WhatsApp page
##?
##? Usage:
##?    whatsapp <number>
##?
##? Examples:
##?    whatsapp 5511999999999

doc::maybe_help "$@"

_launch() {
    dot system open -b "https://web.whatsapp.com/send?phone=$*&text&app_absent=1"
}

main() {
    local number="$(echo "$1" | sed 's|[^0-9]||g')"
    if [[ ${#number} -lt 10 ]]; then
        number="5511${number}"
    fi
    _launch "$number"
}

main "$@"
