#!/usr/bin/env bash
# vim: filetype=sh
set -u

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/package/aux/add.sh"
source "${DOTFILES}/scripts/package/aux/recipes.sh"

##? Install dependencies, abstracting away package managers
##? and custom recipes
##?
##? Usage:
##?    add <deps>...

deps="$(echo "$@" | str::multiline)"
recipes_as_regex="$(recipe::list | xargs | str::regex)"

mkdir -p "$TEMP_FOLDER" 2> /dev/null || true

deps_with_recipe="$(filter::with_recipe "$deps" "$recipes_as_regex" | str::join)"
for dep in $deps_with_recipe; do
   echo
   log::note "Installing ${dep} using custom recipe..."
   recipe::install "$dep"
done

deps_without_recipe="$(filter::without_recipe "$deps" "$recipes_as_regex" | str::join)"
if [[ -n "$deps_without_recipe" ]]; then
   echo
   log::note "Installing ${deps_without_recipe} using system's package manager..."
   pkg="$(platform::main_package_manager)"
   if [[ "$pkg" = "brew" ]]; then
      "$pkg" install "${deps_without_recipe[@]}"
   else
      sudo "$pkg" install "${deps_without_recipe[@]}"
   fi
fi

rm -rf "$TEMP_FOLDER" || true