#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/package/aux/core.sh"
source "${DOTFILES}/scripts/package/aux/recipe.sh"

##? Install packages
##?
##? Usage:
##?    add [options] [<packages>...]
##?
##? Options:
##?    --prevent-recipe

_autocomplete() {
   dot package recipe list
}

doc::maybe_help "$@"

prevent_recipe=false
if [[ "$1" == "--prevent-recipe" ]]; then
   prevent_recipe=true
   shift
fi

if [ $# -gt 1 ]; then
   pkg_failures=0
   for package in "$@"; do
      dot pkg add "$($prevent_recipe && printf %s '--prevent-recipe')" "$package" || pkg_failures=$((pkg_failures+1))
   done
   exit "$pkg_failures"
fi

_log::installing() {
   local suffix=""
   if $prevent_recipe; then
      suffix=" without custom recipes"
   fi
   log::warn "Attempting to install ${package}${suffix}..."
}

main() {
   package="$(pkg::alias "$1" "$prevent_recipe")"

   # shellcheck disable=SC2046
   dot pkg check $($prevent_recipe && printf %s '--prevent-recipe') "$package" && exit 0

   file="$(pkg::source_file "$package")"

   if $prevent_recipe || ! [ -f "$file" ]; then
      _log::installing
      for pkg_mgr in apt apk pkg yum dnf port emerge pacman brew; do
         if dot pkg proxy $pkg_mgr add "$package"; then
            return 0
         fi
      done
      return 234
   fi

   # shellcheck disable=SC1090
   source "$file"

   _log::installing
   package::install && log::success "Finished installing ${package}!"

   hash -r 2>/dev/null || true
   # shellcheck disable=SC1091
   source "${HOME}/.bashrc" 2>/dev/null || true
   # shellcheck disable=SC1091
   source "${HOME}/.zshrc" 2>/dev/null || true
   hash -r 2>/dev/null || true
}

main "$@"