#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/package/aux/core.sh"
source "${DOTFILES}/scripts/core/ini.sh"
source "${DOTFILES}/scripts/core/feedback.sh"

##? Install multiple dependencies
##?
##? Usage:
##?    batch list <name>
##?    batch prompt <name>
##?    batch add <name>

doc::maybe_help "$@"

# show help if no arguments
if [[ $# -lt 1 ]]; then
   "$0" --help
   exit 0
fi

DEP_LIST_FILE="${DOTFILES}/scripts/package/aux/dependencies.ini"

batch::dependencies() {
   local -r name="$1"

   cat "$DEP_LIST_FILE" | ini::get "$name"
}

# input parsing
list=false
prompt=false
add=false
case "${1:-}" in
   list) list=true; shift ;;
   prompt) prompt=true; shift ;;
   add) add=true; shift ;;
esac
name="$1"

_list() {
   batch::dependencies "$name" | xargs | tr ' ' '\n'
}

if $list; then
   _list
   exit 0
fi

install_all_recipes() {
   local -r recipes="$(find "${DOTFILES}/scripts/package/recipes" | sed 's/\.sh$//')"
   for recipe in $recipes; do
      dot pkg add "$recipe"
   done
}

case "$name" in
   "mini") dot pkg batch add "nano" ;;
   "dev") dot pkg batch add "mini" ;;
   "full")
      dot pkg batch add "dev"
      install_all_recipes
      ;;
esac

if $prompt; then
   log::warn "There are missing dependencies for the batch $name"
   if ! feedback::confirmation "Do you want to install it?"; then
      exit 1
   fi
fi

if $add; then
   echoerr add
   IFS=$'\n' 
   for dep in $(batch::dependencies "$name"); do
      dot pkg add "$dep" || true
   done
fi
