#!/usr/bin/env bash
# shellcheck disable=SC2046,SC2015,SC1090,SC1091,SC2034,SC2012,SC2207,SC1090,SC2012
set -euo pipefail

source "${DOTFILES}/scripts/package/aux/core.sh"

##? Check if packages are installed
##?
##? Usage:
##?    add [options] [<packages>...]
##?
##? Options:
##?    --prevent-recipe

doc::maybe_help "$@"

if [[ "$1" == "--prevent-recipe" ]]; then
   prevent_recipe=true
   shift
else
   prevent_recipe=false
fi

if [ $# -gt 1 ]; then
   pkg_failures=0
   for package in "$@"; do
      dot pkg check $($prevent_recipe && printf %s '--prevent-recipe') "$package" || pkg_failures=$((pkg_failures+1))
   done
   exit "$pkg_failures"
fi

exit::is_installed() {
   log::success "${package} is installed"
   exit 0
}

exit::isnt_installed() {
   log::err "${package} isn't installed"
   exit 234
}

package="$(pkg::alias "$1" "$prevent_recipe")"
has "$package" && exit::is_installed

file="$(pkg::source_file "$package")"

if $prevent_recipe || ! [ -f "$file" ]; then
   exit::isnt_installed
fi

source "$file"

if has package::is_installed && package::is_installed &>/dev/null; then
   exit::is_installed
else
   exit::isnt_installed
fi