#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/package/aux/main.sh"

##? Install packages
##?
##? Usage:
##?    install [<packages>...]

opts::eval install "$@"
main