#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/package/aux/core.sh"
source "${DOTFILES}/scripts/package/aux/recipe.sh"

##? Lists custom recipes
##?
##? Usage:
##?    recipe list

doc::maybe_help "$@"

RECIPES_FOLDER="${DOTFILES}/scripts/package/recipes"

recipe::list() {
   cd "${RECIPES_FOLDER}" 
   find . -iname '*.sh' | sed 's|^\./||' | sed 's|\.sh$||'
}

recipe::list