#!/usr/bin/env bash
# shellcheck disable=SC2046,SC2015,SC1090,SC1091,SC2034,SC2012,SC2207,SC1090,SC2012
set -euo pipefail

source "${DOTFILES}/scripts/package/aux/core.sh"
source "${DOTFILES}/scripts/package/aux/recipes.sh"

##? Lists custom recipes
##?
##? Usage:
##?    recipe list

doc::maybe_help "$@"

RECIPES_FOLDER="${DOTFILES}/scripts/package/recipes"

recipe::list() {
   ls "${RECIPES_FOLDER}" \
      | sed 's/\.sh//g'
}

recipe::list