#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Lists custom recipes
##?
##? Usage:
##?    recipe list

docs::eval_help "$@"

RECIPES_FOLDER="${DOTFILES}/scripts/package/recipes"

recipe::list() {
   ls "${RECIPES_FOLDER}" \
      | sed 's/\.sh//g'
}

recipe::list