#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/package/aux/main.sh"

##? Upgrade packages
##?
##? Usage:
##?    upgrade [<packages>...]

opts::eval upgrade "$@"
main