#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Perform transformations over clipboard contents
#?? 0.1.0
##?
##? Usage:
##?     clip <code>
##?
##? Examples:
##?     clip "tr '\n' ' '"

docs::eval "$@"

_transform() {
   local -r input="$1"
   local -r code="$2"
   case $code in
      line) echo "$input" | tr '\n' ' ' ;;
      *) echo "$input" | eval "$code" ;;
   esac
}

input="$(pbpaste)"
result="$(_transform "$input" "$code")"

log::warning "Before"
echo "$input"

echo
log::warning "After"
echo "$result" | tee pbcopy
