#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Displays usage examples for command
#?? 0.1.0
##?
##? Usage:
##?    help <cmd>
##?
##? Examples:
##?    help awk

docs::eval_help "$@"

curl -s "https://cheat.sh/$@"