#!/usr/bin/env bash

source "${DOTFILES}/scripts/core/documentation.sh"

##? identity
#?? 0.1.0
##?
##? Use this command before another one and nothing will change
##? Useful for stubbing/mocking sudo or $
##?
##? Usage:
##?    identity <cmd> <args>...
##?
##? Examples:
##?    identity mv old.txt new.txt

docs::eval_help_first_arg "$@"

"$@"
