#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/functional.sh"

add1() {
   echo $(($1 + 1))
}

add_prefix() {
   echo "file: $1"
}

f::list 1 2 3 | f::sum
echo
f::list 1 2 3 | f::foldl λ var1 var2 → 'echo $var1 $var2'
echo
ls \
   | tr ' ' '\n' \
   | f::filter λ x → 'echo $x | grep -q s' \
   | f::map λ x → 'ls $x' \
   | f::map λ x → 'add_prefix $x' \
   | f::join ', ' [ ]
