#!/usr/bin/env bash

# TODO: finish code
log::warning "WIP code!"

cmd="cat ./peripherals/karabiner/karabiner.json | jq {q} -C"

echo '.' | fzf \
   --ansi \
   --print-query \
   --query="$default_query" \
   --preview="$cmd" \
   --preview-window='up:99%' \
   < /dev/null