#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/documentation.sh"

##? tmux helpers
##?
##? Usage:
##?     tmux new [<session_name>]
##?     tmux attach [<session_name>]
##?     tmux kill [<session_name>]

docs::eval_help "$@"

cmd="${1:-}"
shift

_ls() {
    tmux ls \
        | sed -E 's/^([^:]+): ?/\1|/' \
        | column -t -s'|'
}

_fzf() {
    fzf "$@" 
}

_fzf1() {
    _fzf "$@" | awk '{print $1}'
}

_session() {
    local -r x="$(_ls)"
    [ -z "$x" ] && exit 1

    if [[ $# < 1 ]]; then
       echo "$x" | _fzf1
    else
        echo "$x" | _fzf1 --filter="$*" | head -n1
    fi
}

_new() {
    if [[ $# < 1 ]]; then
        tmux new
    else
        tmux new -s "$*"
    fi
}

_attach() {
    local -r session="$(_session "$@")"
    [ -z "$session" ] && exit 1
    tmux attach -t "$session"
}

_kill() {
    local -r session="$(_session "$@")"
    [ -z "$session" ] && exit 1
    tmux kill-session -t "$session"
}

case $cmd in
    new) _new "$@";;
    attach) _attach "$@";;
    kill) _kill "$@";;
esac