#!/usr/bin/env zsh

source "$DOTFILES/scripts/core/documentation.sh"

##? ZSH helpers
##?
##? Usage:
##?    zsh optimize             # Optimize ZSH
##?    zsh test-performance     # Print the current ZSH performance
##?    zsh reload-completions   # Reload completions

docs::eval_help "$@"

case "${1:-}" in
   *help) extract_help "$0"; exit 0 ;;
esac

case "${1:-}" in
   "optimize")
      /bin/zsh -c "source ${ZDOTDIR:-${HOME}}/.zlogin"
      echo "👌 Done!"
      ;;
   "test-performance")
      for i in $(seq 1 10); do /usr/bin/time /bin/zsh -i -c exit; done
      ;;
   "reload-completions")
      zsh -c "autoload -U compaudit && compinit"
      ;;
   *)
      docs::eval_help --help
      ;;
esac
