#!/usr/bin/env bash
# vim: filetype=sh

##? Arc/Phabricator helper scripts
##?
##? Usage:
##?    diff list

source "${DOTFILES}/scripts/core/documentation.sh"

docs::eval_help "$@"

_list() {
   arc --ansi feature \
      | sed -E 's/\*? ?([^ ]+)(.*)(D[0-9]+):(.*)/\1|\2|\3|\4/' \
      | awk -F'|' 'BEGIN{OFS="|"}
      
      function ltrim(s) { sub(/^[ \t\r\n]+/, "", s); return s } 
      function rtrim(s) { sub(/[ \t\r\n]+$/, "", s); return s }
      function trim(s) { return rtrim(ltrim(s)); } 
      
      { branch = $1; id = $3; $1 = "\033[34m"id"\033[0m"; $2 = trim($2); $3 = trim(branch); $4 = "\033[37m"trim($4)"\033[0m"; print; }' \
      | column -t -s'|' 
}

case "${1:-}" in
   list) _list;;
esac
