#!/usr/bin/env bash

##? Arc/Phabricator helper scripts
##?
##? Usage:
##?    diff list

doc::maybe_help "$@"

_list0() {
   arc --ansi feature \
      | sed -E 's/\*? ?([^ ]+)(.*)(D[0-9]+):(.*)/\1|\2|\3|\4/' \
      | awk -F'|' 'BEGIN{OFS="|"}

      function ltrim(s) { sub(/^[ \t\r\n]+/, "", s); return s }
      function rtrim(s) { sub(/[ \t\r\n]+$/, "", s); return s }
      function trim(s) { return rtrim(ltrim(s)); }

   { branch = $1; id = $3; $1 = "\033[34m"id"\033[0m"; $2 = trim($2); $3 = trim(branch); $4 = "\033[37m"trim($4)"\033[0m"; print; }' \
      | column -t -s'|'
}

_list() {
   arc --ansi list \
      | sed -E 's/^(\* )?(.*)(D[0-9]+):(.*)/\2|\3|\4/' \
      | awk -F'|' 'BEGIN{OFS="|"}

      function ltrim(s) { sub(/^[ \t\r\n]+/, "", s); return s }
      function rtrim(s) { sub(/[ \t\r\n]+$/, "", s); return s }
      function trim(s) { return rtrim(ltrim(s)); }

   { status = $1; id = $2; $1 = "\033[34m"id"\033[0m"; $2 = status; print; }' \
      | column -t -s'|'
}

case "${1:-}" in
   list) _list ;;
esac
