#!/usr/bin/env bash

# if [ -t 1 ]; then
#    exec zsh
# fi

# dotfiles
export DOTFILES="${DOTFILES:-$HOME/dotfiles}"

# register which shell is running
PROFILE_SHELL="bash"

# load vars
source "${DOTFILES}/shell/aux/vars.bash"

# load helper functions
source "${DOTFILES}/shell/aux/core.bash"

# load aliases
source "${DOTFILES}/shell/aliases/core.bash"

# load local custom config
source "${DOTFILES}/local/zshrc" # 2> /dev/null || true

# theme
source "${DOTFILES}/shell/themes/dns.bash"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
