#!/usr/bin/env bash

source "${DOTFILES}/scripts/core/main.sh"

##? Universal clipboard tools
##?
##? Usage:
##?     clip copy
##?     clip paste
##?     clip map <args>...

doc::parse "$@"

operation="$1"
shift

_copy() {
   if has pbcopy; then
      pbcopy
   elif has xclip; then
      xclip -selection clipboard
   elif has clip.exe; then
      clip.exe
   elif has clip; then
      clip
   else
      die "No available clipboard tool"
   fi
}

_paste() {
   if has pbpaste; then
      pbpaste
   elif has xclip; then
      xclip -selection clipboard -o
   elif has powershell.exe; then
      powershell.exe Get-Clipboard | sed 's/\r$//'
   elif has powershell; then
      powershell Get-Clipboard | sed 's/\r$//'
   else
      die "No available clipboard tool"
   fi
}

_map() {
   _paste | "$@" | _copy
}

case $operation in
   copy) _copy ;;
   paste) _paste ;;
   map) _map "$@" ;;
esac
