#!/usr/bin/env bash

source "${DOTFILES}/scripts/core/main.sh"

##? Colorize output
##?
##? Usage:
##?     color
##?
##? Examples:
##?     ls > >(color)

doc::maybe_help "$@"

main() {
   while read line; do
      dot terminal ansi --yellow "$line"
   done
}

main "$@"