#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/platform.sh"

##? Use current path as argument if none is specified
##
##? Usage:
##?     dashed <cmds>... [-- [<args>...]]?
##
##? Example:
##?     dashed ls -la
##?     dashed ls -la -- somefolder

doc::maybe_help "$@"

indexof() {
   local -r index="$1"
   i=0;
   shift
   # shellcheck disable=SC2198
   while [ "$i" -le "$#" ]; do
      if [ "${@:$i:1}" = "$index" ]; then
         echo $i
         return
      fi
      ((i++));
   done;
   echo -1;
}

get_fn() {
   IFS=',' read -r -a args <<< "$1"
   platform::existing_command "${args[@]}"
}

dot_or_args() {
   local -r dash_index="$(indexof "--" "$@")"
   
   local args=()
   args=("${@:2:$((dash_index-2))}")

   local -r fn1s="$1"
   local -r fn1="$(get_fn "$fn1s")"

   shift "$dash_index"

   # echo "len args: ${#args[@]}; len @: $#" 
   # echo "args[0]: ${args[0]:-nil}" 

   if [ $# -lt 1 ]; then
      set -- "."
   fi

   args=("${args[@]}" "$@")

   # set -x
   "$fn1" "${args[@]:-}"
}

dot_or_args "$@"
