#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Use current path as argument if none is specified
##
##? Usage:
##?     dashed <cmds>... [-- [<args>...]]?
##
##? Example:
##?     dashed ls -la
##?     dashed ls -la -- somefolder

doc::maybe_help "$@"

indexof() {
   local -r index="$1"
   i=0;
   shift
   # shellcheck disable=SC2198
   while [ "$i" -le "$#" ]; do
      if [ "${@:$i:1}" = "$index" ]; then
         echo $i
         return
      fi
      ((i++));
   done;
   echo -1;
}

dot_or_args() {
   local -r dash_index="$(indexof "--" "$@")"
   # shellcheck disable=SC2124
   readonly fn="${@:1:$((dash_index-1))}"
   shift "$dash_index"
   if [[ $# -lt 1 ]]; then
      # shellcheck disable=SC2068
      ${fn[@]} .
   else
      # shellcheck disable=SC2068
      ${fn[@]} "$@"
   fi
}

dot_or_args "$@"