#!/usr/bin/env bash

source "${DOTFILES}/scripts/core/main.sh"

##? Expand bashrc-like files
##?
##? Usage:
##?    expand

doc::maybe_help "$@"

_expand() {
   local -r filename="$1"

   while read line || [ -n "$line" ]; do
      if [[ "$line" == source* ]]; then
         file="$(echo "$line" | cut -d' ' -f2)"
         file="$(eval echo "$file")"
         if echo "$file" | grep -q "modules/zsh"; then
            echo "$line"
         else
            echoerr "bundling $file..."
            dot sh expand "$file"
         fi
      else
         echo "$line"
      fi
   done < "$filename"
}

file="${1:-"${DOTFILES}/shell/zsh/zshrc"}"
_expand "$file"
