#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Log helper
##?
##? Usage:
##?    header|warn|err|success|info <args>...
##?    sep <args>...

doc::maybe_help "$@"

_sep() {
   for _ in $(seq 0 300); do
      echo
   done

   clear

   log::trace "$(date)"

   for _ in $(seq 0 5); do
      echo
   done
}

main() {
   local -r fn="$1"
   shift

   case "$fn" in
      sep) _sep "$@"; return 0 ;;
   esac

   "log::${fn}" "$@"
}

main "$@"