#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Open files/folders
##?
##? Usage:
##?    open [options] <args>...
##?
##? Options:
##?    -b --browser      Open using the browser
##?
##? Examples:
##?    open http://google.com

doc::parse "$@"

_open() {
   if has open; then
      open "$@"
   elif has xdg-open; then
      xdg-open "$@"
   else
      exit 1
   fi
}

_browser_cmd() {
   if has vivaldi; then
      echo "vivaldi" && return 0
   elif has google-chrome; then
      echo "google-chrome" && return 0
   elif has chrome; then
      echo "chrome" && return 0
   elif has firefox; then
      echo "firefox" && return 0
   fi

   local file="/Applications/Vivaldi.app/Contents/MacOS/Vivaldi"
   if [ -f "$file" ]; then
      echo "$file" && return 0
   fi

   file="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
   if [ -f "$file" ]; then
      echo "$file" && return 0
   fi

   exit 1
}

_open_browser() {
   local -r cmd="$(_browser_cmd)"
   "$cmd" "$@"
}

if $browser; then
   shift
   _open "$@"
else
   _open "$@"
fi
