#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/test.sh"

##? Test runner
##?
##? Usage:
##?    test <folder> [<args>...]

doc::maybe_help "$@"

main() {
   test::start "$@"
}

main "$@"