#!/usr/bin/env bash
set -eo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Color
#?? 0.2.0
##?
##? Usage:
##?    color print <rgb>...
##?    color hex <r> <g> <b>
##?    color rgb <hex>

docs::eval_help "$@"

_row() {
   for i in $(seq 1 $cols); do
      echo -n "█"
   done
}

_as_printf_color() {
   local -r color="$1"
   local c
   [ ${color:0:1} == "#" ] && c=${color:1} || c="$color"
   echo "$c" \
      | str::uppercase \
      | sed -E 's/([0-9A-Fa-f]{2})([0-9A-Fa-f]{2})([0-9A-Fa-f]{2})/\1\n\2\n\3/' \
      | xargs -I% sh -c "echo 'ibase=16; %' | bc" \
      | tr '\n' ';'
}

_print_colors() {
   local -r row="$(_row)"
   local -r rows=$(echo "${COLS:-5} * 3 / 5" | bc)
   local i color c
   for i in $(seq 1 $rows); do
      for color in $@; do
         c="$(_as_printf_color "$color")"
         printf "\x1b[38;2;${c}m${row}\x1b[0m "
      done
      echo
   done
}

_rgb_to_hex() {
   echo "$(printf \#%02X%02X%02X "$@")"
}

_hex_to_rgb() {
   local -r hex="$(echo "$1" | tr -d '#')"
   echo "$(printf "%d %d %d\n" 0x${hex:0:2} 0x${hex:2:2} 0x${hex:4:2})"
}

operation="$1"
shift

case "$operation" in 
   print) _print_colors "$@" ;;
   hex) _rgb_to_hex "$@" ;;
   rgb) _hex_to_rgb "$@" ;;
esac
