#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Lock screen
#?? 0.1.0
##?
##? Usage:
##?    lock

docs::eval_help "$@"

if ! platform::is_osx; then
   die "Command not implemented for your current platform!"
fi

pmset displaysleepnow