#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/platform.sh"

##? Open files/folders
##?
##? Usage:
##?    open <args>...
##?
##? Examples:
##?    open http://google.com

doc::parse "$@"

_open() {
   if platform::is_osx; then
      open "$@" & disown
   else
      xdg-open "$@" & disown
   fi
}

_open "${args[@]:-}"
