#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/platform.sh"

##? Open files/folders
##?
##? Usage:
##?    open [options] <args>...
##?
##? Options:
##?    -b --browser      Open using the browser
##?
##? Examples:
##?    open http://google.com

doc::parse "$@"

_open() {
   if platform::is_osx; then
      open "$@" & disown
   else
      xdg-open "$@" & disown
   fi
}

_browser_cmd() {
   local -r file="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
   
   if has google-chrome; then
      echo "google-chrome"
   elif has chrome; then
      echo "chrome"
   elif has firefox; then
      echo "firefox"
   elif [ -f "$file" ]; then
      echo "$file"
   else
      exit 1
   fi
}

_open_browser() {
   local -r cmd="$(_browser_cmd)"
   "$cmd" "$@"
}

if $browser; then
   _open_browser "$@"
else
   _open "$@"
fi
