#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Shows mission control space info
#?? 0.1.0
##?
##? Usage:
##?    spaces

docs::eval "$@"

if ! platform::is_osx; then
   die "Command not implemented for your current platform!"
fi

spaces="$(defaults read com.apple.spaces)"

echo "$spaces" \
   | grep -n 'paces =' \
   | awk '{print $1}' \
   | sed 's/.$//'

echo "$spaces" \
   | sed -n '73,9999p'
