#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Window manager utilities
##?
##? Usage:
##?    wm cheats navi
##?
##? Examples:
##?    wm cheats

doc::maybe_help "$@"

_last_word() {
   echo "${1##* }"
}

_print_navi() {
   local -r comment="$1"
   local -r cmd="$2"
   local -r hotkey="$3"
   printf "%-36s %-20s %s\n" "$comment" "$hotkey" "$cmd"
}

_print() {
   print_fn="$1"
   should_start=false
   comment=""
   cat "${DOTFILES}/peripherals/skhd/skhd.rc" | while read -r line; do
      if ! $should_start; then
         case $line in
            *Power*) should_start=true ;;
         esac
         continue
      fi
      case $line in
         *EOF*) return 0 ;;
      esac
      if [[ "$line" == \#* ]]; then
         comment="${line:2}"
         last_word="$(_last_word "$comment")"
         case "$last_word" in
            direction|space) should_replace=true ;;
            *) should_replace=false ;;
         esac
      else
         hotkey="$(echo "$line" | cut -d':' -f1 | sed 's/alt + cmd + ctrl + shift/hyper/g')"
         cmd="$(echo "$line" | cut -d':' -f2)"
         if $should_replace; then
            replacement="$(_last_word "$cmd")"
            new_comment="$comment $replacement"
         else
            new_comment="$comment"
         fi
         $print_fn "$new_comment" "${cmd:1}" "$hotkey"
      fi
   done
}

_navi() {
   _print _print_navi
}

target="${2:-}"
case $target in
   *) _navi ;;
esac
