#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? cat/pager utility abstraction
##?
##? Usage:
##?    less [<args>...]

doc::maybe_help "$@"

# argument parsing
args=()
variable=""
for arg in "$@"; do
   if [[ $arg == "--filename" ]]; then
      variable="filename"
   elif [[ -n $variable ]]; then
      eval "$variable"='"$arg"'
      variable=""
   else
      args+=("$arg")
   fi
done

_less() {
   less -R "$@"
}

# fallback in case of missing binaries
if ! has bat; then
   _less "$@"
   exit 0
fi

# language inference
language=""
if [[ -n "${filename:-}" ]]; then
   language="${filename##*.}"
   args+=("--language=${language}")
fi

# call
case $language in
   json) jq -C . | _less ;;
   *) bat --plain --color=always "${args[@]}" | _less ;;
esac
