#!/usr/bin/env bash

source "$DOTFILES/scripts/core/main.sh"

##? (Experimental) navi helper for commands with one argument
##?
##? Usage:
##?    navi <query> <var> [<value>]

doc::maybe_help "$@"

main() {
    local -r query="$1"
    local -r var="$2"
    shift 2

   if [[ $# -gt 0 ]]; then
      local -r var_full="${var}__best"
      read $var_full <<< "$*"
      export $var_full
   fi

   navi --query "$query" --best-match
}

main "$@"