#!/usr/bin/env zsh

##? ZSH helpers
##?
##? Usage:
##?    zsh optimize             # Optimize ZSH
##?    zsh benchmark            # Print the current ZSH performance
##?    zsh reload-completions   # Reload completions

_benchmark() {
   env | grep "DOT_"
   hyperfine '/usr/bin/time /bin/zsh -i -c exit' --warmup 1
}

case "${1:-}" in
   opt*)
      /bin/zsh -c "source ${ZDOTDIR:-${HOME}}/.zlogin"
      echo "👌 Done!"
      ;;
   *perf*|bench*)
      DOT_ZIM=false _benchmark
      _benchmark
      ;;
   *comp*)
      zsh -c "autoload -U compaudit && compinit"
      ;;
   *)
      source "$DOTFILES/scripts/core/main.sh"
      doc::maybe_help --help
      ;;
esac
