#!/bin/bash

cd $HOME
folders=$(ls)

add_item() {
	echo "${1}<items><item uid=\"asda\" arg=\"asd\">
		<title>${2}</title>
		<subtitle>fsdfsd</subtitle>
	</item>"
}

xml="<items>"
for folder in $folders; do
	add_item "$xml" "$folder"
done
xml="${xml}</items>"

echo "$xml"
