#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Source code indentation fixer
##?
##? Usage:
##?    beautify <filename>

docs::eval "$@"

_get_language() {
   local -r filename="$1"
   local extension="${filename##*.}"
   local language

   if echo "$extension" | grep -q '/'; then
      extension=""
   fi

   case "$extension" in
      *sh) language="sh" ;;
      *clj*) language="clj" ;;
      *py*) language="python" ;;
      *json*) language="json" ;;
      *js*) language="javascript" ;;
      *rs) language="rust" ;;
   esac

   if [ -z $extension ]; then
      if cat "$filename" | head -n3 | grep -q "sh$"; then
         language="sh"
      fi
   fi

   echo "${language:-fallback}"
}

language=${language:-$(_get_language "$filename")}

log::warning "formatting $filename as <${language}>"
case "$language" in
   sh_old)
      shfmt -w -i 3 -ci -bn "$filename"
      ;;
   sh)
      beautysh -i 3 -s paronly "$filename"
      sed -i -e 's/() ::/::/g' "$filename"
      ;;
   json)
      echo "$(cat "$filename" | jq .)" > "$filename"
      ;;
   javascript)
      js-beautify "$filename" > /dev/null
      ;;
   rust)
      rustfmt "$filename"
      ;;
   *)
      nvim --headless --noplugin -n -u NONE -c ':normal gg=G' +wq "$filename"
      ;;
esac
