#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Source code indentation fixer
##?
##? Usage:
##?    column

docs::eval "$@"

sed -E 's/(\w)\s+/\1%/' \
  | column -s% -t \
  | sed 's/%/ /'
