#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/main.sh"

_keys() {
   cat "${DOTFILES}/editors/sublime/preferences.json" \
      | jq -rc 'path(..)|[.[]|tostring]|join(".")'
}

_main() {
   _keys \
      | fzf --preview "$0 preview"
}

_preview() {
   echo -e "$(log::ansi red)CPU percent usage"
   echo -e
   echo -e "$(log::ansi blue)Current value:"
   echo -e "$(log::ansi cyan)70"
   echo -e
   echo -e "$(log::ansi blue)Possible values:"
   echo -e "$(log::ansi cyan)0 <= x <= 100"
   echo -e
   echo -e "$(log::ansi reset)Relevant URL:"
   echo -e "https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale"
}

case "${1:-}" in
   preview) _preview "$@" ;;
   *) _main "$@" ;;
esac
