#!/usr/bin/env bash

source "${DOTFILES}/scripts/core/main.sh"

##? Source code indentation fixer
##?
##? Usage:
##?    parser json [<path>]
##?    parser yaml [<path>]

type="$1"
path="${2:-}"

if [[ -n $path ]]; then
   content="$(cat "$path")"
else
   content="$(cat)"
fi

submodule::clone() {
   local readonly module="$1"
   local readonly probe_file="$2"
   local readonly probe_path="${DOTFILES}/modules/${module}/${probe_file}"  
   if ! fs::is_file "$probe_path"; then
     git submodule update --init "modules/${module}"
   fi
}

case $type in
   j*)
      submodule::clone "json-sh" "JSON.sh"
      echo "$content" | "${DOTFILES}/modules/json-sh/JSON.sh" > /dev/null
      ;;
   y*)
      submodule::clone "bash-yaml" "script/yaml.sh"
      source "${DOTFILES}/modules/bash-yaml/script/yaml.sh"
      parse_yaml <(echo "$content") > /dev/null
      ;;
esac
