#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/self/aux/update.sh"

##? Checkout itself to latest branch
##?
##? Usage:
##?    checkout

docs::eval_help "$@"

cd "$DOTFILES"
git pull
dot git checkout latest
