#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Checkout itself to latest branch
##?
##? Usage:
##?    checkout

docs::eval_help "$@"

cd "$DOTFILES"
git pull
dot git checkout latest
