#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Starts a minimal docker container with these dotfiles
##?
##? Usage:
##?    docker <script>

doc::maybe_help "$@"

case "${1:-}" in
   install) SCRIPT="EDITOR=cat DOT_INSTANCE=devpod-br dot self install --profile devpod" ;;
   *) SCRIPT=":" ;;
esac

docker run \
   -it \
   --entrypoint /bin/bash \
   -v "${DOTFILES}:/dotfiles" \
   "bashell/alpine-bash" \
   -c "export DOTFILES=/dotfiles; export EDITOR=vi; export PATH=${PATH}:/dotfiles/bin; $SCRIPT; bash"
