#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Starts a minimal docker container with these dotfiles
##?
##? Usage:
##?    docker <script>

doc::maybe_help "$@"

case "${1:-}" in
   install) SCRIPT="DOT_INSTANCE=devpod /root/dotfiles/bin/dot self install --profile devpod" ;;
   *) SCRIPT=":" ;;
esac

docker run \
   -it \
   --entrypoint /bin/bash \
   -v "${DOTFILES}:/root/dotfiles" \
   "bashell/alpine-bash" \
   -c "$SCRIPT; bash"
