#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Checks for available commands, config files, etc.
##?
##? Usage:
##?    health

docs::eval "$@"

CODE=0

main() {

   echo
   log::header "Shell"
   check_commands "ruby python git zsh tmux fasd ag tmuxinator fzf curl"
   check_dir "$HOME/.tmux/plugins/tpm" "tpm"

   if platform::is_osx; then
      echo
      log::header "GNU commands"
      check_gnu_commands "sed grep" true
   fi

   echo
   log::header "Editors"
   check_commands "vim nvim emacs"
   check_file "$HOME/.local/share/nvim/site/autoload/plug.vim" "vim-plug"

   echo
   log::header "Local git"
   check_file "$DOTFILES/local/gitconfig" "config"

   echo
   log::header "Misc"
   check_commands "unzip ranger tig ag bat htop clojure lein node"

   echo
   log::header "dotfiles"
   check_env "DOTFILES"
   check_commands "dot"

}

check_command_available() {
   local cmd="$1"
   if platform::command_exists "$cmd"; then
      log::success "$cmd"
   else
      inc_error "$cmd"
   fi
}

check_gnu_command_available() {
   local cmd
   if platform::is_osx; then
      cmd="g$1"
   else
      cmd="$1"
   fi
   check_command_available "$cmd"
}

check_commands() {
   local cmds="$1"
   for cmd in $cmds; do
      check_command_available "$cmd"
   done
}

check_gnu_commands() {
   local cmds="$1"
   for cmd in $cmds; do
      check_gnu_command_available "$cmd"
   done
}

check_vim_plug() {
   if fs::is_file $HOME/.local/share/nvim/site/autoload/plug.vim; then
      log::success "vim-plug"
   else
      inc_error "vim-plug"
   fi
}

check_file() {
   local path="$1"
   local name="$2"
   if fs::is_file "$path"; then
      log::success "$name"
   else
      inc_error "$name"
   fi
}

check_dir() {
   local path="$1"
   local name="$2"
   if fs::is_dir "$path"; then
      log::success "$name"
   else
      inc_error "$name"
   fi
}

check_env() {
   set +u
   [[ -z "${!1}" ]] && {
      inc_error "\$$1"
   } || log::success "\$$1"
   set -u
}

inc_error() {
   log::error "$1"
   CODE=$(($CODE + 1))
}

main "$@"
exit $CODE
