#!/usr/bin/env bash
set -euo pipefail

export DOTFILES="${DOTFILES:-$HOME/.dotfiles}"
REPO="https://github.com/denisidoro/dotfiles.git"
DOT_BIN="${DOTFILES}/bin/dot"

##? Setups the environment
#?? 0.3.0
##?
##? Usage:
##?    init

_dot() {
   "$DOT_BIN" "$@"
}

clone_repo() {
   git clone "$REPO" "$DOTFILES"
}

# Pushes the current directory to the stack
pushd . >/dev/null


if [ -f "$DOT_BIN" ]; then
   printf ''
elif [ -f "$DOTFILES" ]; then
   echo "Backing up existing .dotfiles folder and cloning new .dotfiles..."
   old_dotfiles=$(mktemp -u -d "${DOTFILES}_XXXX")
   mv "$DOTFILES" "$old_dotfiles"
   clone_repo
else
   echo "No .dotfiles folder found. Installing dependencies and cloning .dotfiles..."
   clone_repo
fi

cd "$DOTFILES"

# Android bootstrap
if uname -a | grep -q "ndroid"; then
   pkg install ncurses-utils
fi

# OSX bootstrap
if uname -s | grep -q "arwin"; then
   _dot pkg add gnu
fi

# call setup
_dot self update

# cleanup
popd >/dev/null

exec "$SHELL"
