#!/usr/bin/env bash

##? Symlink handler
#?? 0.1.0
##?
##? Usage:
##?    link <args>...

export DOTFILES="${DOTFILES:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)}"
export DOT_REPO="https://github.com/denisidoro/dotfiles.git"
export DOT_DIR="$DOTFILES"
export DOT_LINK="${DOTFILES}/links/${DOTLINK:-"unix"}.yaml"

source "${DOTFILES}/modules/dotlink/dotlink"

dotlink_main "$@"
