#!/usr/bin/env bash

##? Symlink handler
##?
##? Usage:
##?    link <args>...

export DOTFILES="${DOTFILES:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)}"
export DOT_REPO="https://github.com/denisidoro/dotfiles.git"
export DOT_DIR="$DOTFILES"
export DOT_LINK="${DOTFILES}/links/${DOTLINK:-"unix"}.csv"

main() {
    dot link set "$@"
}

main "$@"