#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Pulls the latest version of the dotfiles
##?
##? Usage:
##?    pull

docs::eval_help "$@"

cd "${DOTFILES}"
dot git checkout latest
git pull
