#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/coll.sh"

##? Generate symlinks
#?? 0.1.0
##?
##? Usage:
##?    symlinks
##?    symlinks <group>

docs::eval_help "$@"

expanded() {
   local -r x="$(echo "$*" | sed 's/~/$HOME/g')"
   eval "echo \"$x\""
}

gen_ln() { 
   local -r input="$1"
   local -r target="$(echo "$input" | awk -F'|' '{print $1}')"
   local -r src="$(echo "$input" | awk -F'|' '{print $2}')"
   ln -s "${DOTFILES}/${src}" "$(expanded "$target")"
}

extract_map() {
   grep '^- link' -A999 \
      | tail -n +2 \
      | sed 's/: /|/g'
}

full_filename() {
   local -r group="$1"

   if [ -n "$group" ]; then
      echo "${DOTFILES}/symlinks/conf.${group}.yaml"
   else
      echo "${DOTFILES}/symlinks/conf.yaml"
   fi
}

filename="$(full_filename "${1:-}")"
dotbot_bin="${DOTFILES}/${DOTBOT_DIR}/${DOTBOT_BIN}"

if [ -f "$dotbot_bin" ]; then
      shift
      echo
      "${DOTFILES}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "$DOTFILES" -c "$filename" "${@}"
      echo
else
   echo "$filename" \
   | extract_map \
   | coll::map gen_ln
fi
