#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/self/aux/test.sh"

##? Run tests
##?
##? Usage:
##?    test
##?    test suite <suite>
##?    test file <file>

docs::eval_help "$@"

_all_files() {
   find "${DOTFILES}/tests/" -iname "*.sh"
}

cmd="${1:-}"

case $cmd in
   file) export TEST_FILTER="$2" ;;
   suite) export TEST_FILTER="^${2} \-"  ;;
   *) ;;
esac

echo "$TEST_FILTER"
for test in $(_all_files); do
   source "$test"
done

test::finish
