#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/self/aux/test.sh"

##? Run tests
##?
##? Usage:
##?    test
##?    test <suite>

docs::eval_help "$@"

if [ $# > 0 ]; then

  source "${DOTFILES}/tests/${1}.sh"

else

  tests="$(find "${DOTFILES}/tests/" -iname "${1:-*}.sh")"

  for test in $tests; do
     source "$test"
  done

fi

test::finish
