#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/str.sh"
source "${DOTFILES}/scripts/core/platform.sh"
source "${DOTFILES}/scripts/core/log.sh"

##? Updates submodules, dotfiles and attempts to do some setup
##?
##? Usage:
##?    update

doc::maybe_help "$@"

main() {
   log::info "Updating dotfiles\n$(_version)\n"
   echoerr

   set +e

   tags="$(platform::tags)"
   log::info "Current config: $tags"
   echoerr

   if ! ${DOT_INSTALL_SKIP_CORE_DEPS:-false}; then
      _add dot-submodules || true
      _add dot-folders || true
      _add dot-gitconfig || true
      _add dot-zshrc || true
   fi

   echoerr
   log::info "Setting symlinks..."
   update_dotfiles_common
   has_tag "$tags" "osx" && update_dotfiles_osx
   has_tag "$tags" "linux" && update_dotfiles_linux
   has_tag "$tags" "arm" && update_dotfiles_arm
   has_tag "$tags" "x86" && update_dotfiles_x86
   has_tag "$tags" "android" && update_dotfiles_android
   has_tag "$tags" "wsl" && update_dotfiles_wsl
   has_tag "$tags" "work" && update_dotfiles_work

   fix_locales || true

   set -e

   echoerr
   log::success "Update finished!"
}

# ==============================
# Helpers
# ==============================

has_tag() {
   str::contains "$@"
}

_version() {
   dot --version || echo "unknown"
}

_add() {
   log::warn "dot pkg add $*"
   dot pkg add "$@"
}

# ==============================
# Locale
# ==============================

fix_locales() {
   if has locale-gen; then
      echoerr
      log::info "Fixing locales..."
      locale-gen en_US en_US.UTF-8
   fi
}

# ==============================
# Symlinks and custom configs
# ==============================

update_dotfiles() {
   DOTLINK="${1:-unix}" dot self link set --create-dirs --verbose
}

update_dotfiles_common() {
   log::info "Symlinking for Unix..."
   update_dotfiles
}

update_dotfiles_osx() {
   log::info "Symlinking for OSX..."
   update_dotfiles "osx"
}

update_dotfiles_linux() {
   log::info "Symlinking for Linux..."
   update_dotfiles "linux"
}

update_dotfiles_wsl() {
   log::info "Symlinking for WSL..."
   update_dotfiles "linux"
}

update_dotfiles_arm() {
   log::info "Symlinking for ARM..."
   log::info "No custom config for ARM"
}

update_dotfiles_x86() {
   log::info "Symlinking for x86..."
   log::info "No custom config for x86"
}

update_dotfiles_android() {
   log::info "Symlinking for Android..."
   dot pkg add termux-essentials || true
   update_dotfiles "android"
}

update_dotfiles_work() {
   log::info "Symlinking for work..."
   update_dotfiles "work"
}

# ==============================
# Script root
# ==============================

main "$@"