#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Makes a script executable
##?
##? Usage:
##?    x <ctx> <cmd>

docs::eval "$@"

chmod +x "${DOTFILES}/scripts/${ctx}/${cmd}"
