#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/core/str.sh"

##? Helpers for retrieving grids
##?
##? Usage:
##?    grid <game>

doc::parse "$@"

query="$(str::urlencode "$game")"

url="$(curl -s "https://www.steamgriddb.com/search/${query}/alternate,blurred,white_logo,no_logo,material" \
  | grep -Eo 'http.*/grid/[^"]*png' \
  | head -n1)"

curl -s "$url" | imgcat