#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Playnite helpers
##?
##? Usage:
##?    playnite games
##?    playnite set

docs::eval "$@"

LIBRARY_DIR="${HOME}/Downloads/library"

if $games; then
   cat $LIBRARY_DIR/games/* | jq -r '.Name'
elif $set; then
   game="$(cat $LIBRARY_DIR/games/* \
        | jq -r '.Name' \
        | fzf --height '50%')"
   dot gaming images "$game"
fi
