#!/usr/bin/env zsh

# set +x

# dotfiles
export DOTFILES="${DOTFILES:-"${HOME}/dotfiles"}"

# load vars
source "${DOTFILES}/shell/aux/vars.bash"

# load helper functions
source "${DOTFILES}/shell/aux/core.bash"

# load aliases
source "${DOTFILES}/shell/aliases/core.bash"

# load local custom config
source "${DOTFILES}/local/zshrc" 2> /dev/null || true
source "${DOTFILES}/local/${DOT_INSTANCE}/zshrc" 2> /dev/null || true

# on directory change
if has fre; then
   dns_chpwd() {
      fre --add "$PWD"
   }
   typeset -gaU chpwd_functions
   chpwd_functions+=dns_chpwd
fi

# history
setopt HIST_IGNORE_ALL_DUPS

# load bindings
source "${DOTFILES}/shell/zsh/bindings/editing.zsh"
has navi && source "${DOTFILES}/shell/zsh/bindings/navi.zsh"
has fzf && source "${DOTFILES}/shell/zsh/bindings/fzf.zsh"

# theme
export DOT_THEME="${DOT_THEME:-none}"
# if [ "$DOT_THEME" != "none" ]; then
   source "${DOTFILES}/shell/themes/core.zsh"
# fi

# misc
# WORDCHARS=${WORDCHARS//[\/]}

# zim
if [[ "$DOT_THEME" == "powerlevel" ]]; then
   # source ${ZIM_HOME}/login_init.zsh -q &!

   # if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
   #    # Update static initialization script if it's outdated, before sourcing it
   #    source ${ZIM_HOME}/zimfw.zsh init -q
   # fi

   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
   source "${ZIM_HOME}/init.zsh"
   source "${DOTFILES}/shell/zsh/bindings/zim.zsh"
fi


# in order not to mess up with subshells
export ZDOTDIR="$HOME"

# nnn
# export NNN_PLUG="f:fzcd;o:fzopen;z:fzz;d:diffs;t:treeview;v:preview-tui"
# export NNN_FIFO="/tmp/nnn.fifo"

# $ alias
# alias \$=''

# zmodload zsh/zprof (in /etc/zshenv)
# zprof

# set -x