#!/usr/bin/env zsh

# dotfiles
export DOTFILES="${DOTFILES:-"${HOME}/dotfiles"}"

# register which shell is running
PROFILE_SHELL="zsh"

# load vars
source "${DOTFILES}/shell/aux/vars.bash"

# load helper functions
source "${DOTFILES}/shell/aux/core.bash"

# load aliases
source "${DOTFILES}/shell/aliases/core.bash"

# load local custom config
source "${DOTFILES}/local/zshrc" # 2> /dev/null || true

# zim
if ${DOT_ZIM:-false}; then
   # source ${ZIM_HOME}/login_init.zsh -q &!

   if [[ ${ZIM_HOME}/init.zsh -ot ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
   # Update static initialization script if it's outdated, before sourcing it
   source ${ZIM_HOME}/zimfw.zsh init -q
   fi
   source ${ZIM_HOME}/init.zsh
fi

# on directory change
dns_chpwd() {
   if ${DOT_FRE:-true}; then
      fre --add "$PWD"
   fi
}
typeset -gaU chpwd_functions
chpwd_functions+=dns_chpwd

# history
setopt HIST_IGNORE_ALL_DUPS

# theme
source "${DOTFILES}/shell/themes/core.zsh"

# load bindings
source "${DOTFILES}/shell/zsh/bindings/editing.zsh"
[[ ${DOT_NAVI:-false} ]] && source "${DOTFILES}/shell/zsh/bindings/navi.zsh"
[[ ${DOT_ZIM:-false} ]] && source "${DOTFILES}/shell/zsh/bindings/zim.zsh"
[[ ${DOT_FZF:-false} ]] && source "${DOTFILES}/shell/zsh/bindings/fzf.zsh"

# misc
WORDCHARS=${WORDCHARS//[\/]}

# set path for completions
fpath=("${DOTFILES}/shell/zsh/completions" $fpath)
