#!/usr/bin/env bash
set -euo pipefail

PROJ_BIN="${DOTFILES}/target/dotrs"
RELEASE_BIN="target/release/dotrs"
DEBUG_BIN="target/debug/dotrs"

_bin() {
   if [ -f "$PROJ_BIN" ]; then
      echo "$PROJ_BIN"
      return 0
   elif [ -f "$RELEASE_BIN" ]; then
      echo "$RELEASE_BIN"
      return 0
   elif [ -f "$DEBUG_BIN" ]; then
      echo "$DEBUG_BIN"
      return 0
   fi
   return 1
}

_help() {
   echo "Calls Rust commands

Usage:
   call <cmd>"
   exit 0
}

_call() {
   local -r cmd="$1"
   local -r bin_path="$(_bin)"

   if [ -n "$bin_path" ]; then
      $bin_path "$@"
      exit 0
   fi
   return 1
}

cmd="${1:-}"
case "$cmd" in
   --help|-h) _help ;;
esac

_call "$@" && exit 0
dot pkg add dotrs || true
_call "$@" && exit 0
