#!/usr/bin/env bash
set -euo pipefail

PROJ_HOME="${PROJ_HOME:-$DOTFILES}"
PROJ_NAME="${PROJ_NAME:-dotrs}"
PROJ_BIN="${PROJ_BIN:-${DOTFILES}/target/${PROJ_NAME}}"
RELEASE_BIN="${PROJ_HOME}/target/release/${PROJ_NAME}"
DEBUG_BIN="${PROJ_HOME}/target/debug/${PROJ_NAME}"

_bin() {
   if [ -f "$PROJ_BIN" ]; then
      echo "$PROJ_BIN"
      return 0
   elif [ -f "$RELEASE_BIN" ]; then
      echo "$RELEASE_BIN"
      return 0
   elif [ -f "$DEBUG_BIN" ]; then
      echo "$DEBUG_BIN"
      return 0
   fi
   return 1
}

_help() {
   echo "Calls Rust commands

Usage:
   call <cmd>"
   exit 0
}

_call() {
   local -r cmd="$1"
   local -r bin_path="$(_bin)"

   if [ -n "$bin_path" ]; then
      $bin_path "$@"
      exit 0
   fi
   return 1
}

_call "$@" && exit 0

dot pkg add dotrs || true
_call "$@" && exit 0
