#!/usr/bin/env bash
set -euo pipefail

##? Apply lint and fmt fixes
##?
##? Usage:
##?    fix

source "${DOTFILES}/scripts/rust/aux/proj.sh"

doc::parse "$@"

cd "$PROJ_HOME"

log::warn "Cargo fmt..."
cargo fmt || true

log::warn "Cargo nighly fix..."
cargo +nightly clippy --fix -Z unstable-options || true

log::warn "Cargo fix..."
cargo fix || true

log::warn "clippy..."
cargo clippy || true
