#!/usr/bin/env bash
set -euo pipefail

##? Apply lint and fmt fixes
##?
##? Usage:
##?    fix

source "${DOTFILES}/scripts/rust/aux/proj.sh"

docs::eval "$@"

cd "$PROJ_HOME"

header "Cargo fmt..."
cargo fmt || true

header "Cargo nighly fix..."
cargo +nightly clippy --fix -Z unstable-options || true

header "Cargo fix..."
cargo fix || true

header "clippy..."
cargo clippy || true
