#!/usr/bin/env bash
set -euo pipefail

##? make install
##? make uninstall

source "${DOTFILES}/scripts/rust/aux/proj.sh"

install() {
   export SOURCE_DIR="${SOURCE_DIR:-"$(get_source_dir)"}"
   export BIN_DIR="${BIN_DIR:-"$(get_bin_dir)"}"
   echoerr "The final binary will be available at ${BIN_DIR}/${PROJ_NAME}..."
   "${PROJ_HOME}/scripts/action" release
   ln -s "${PROJ_HOME}/target/tar/${PROJ_NAME}" "${BIN_DIR}/${PROJ_NAME}"
}

uninstall() {
   export SOURCE_DIR="${SOURCE_DIR:-"$(get_source_dir)"}"
   rm -rf "${PROJ_HOME}/target"
   rm "$SOURCE_DIR"
}

cmd="$1"
shift

case "$cmd" in
   "install") install "$@" ;;
   "uninstall") uninstall "$@" ;;
esac
