#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/rust/aux/core.bash"

main() {
   dot termuxpc push \
      "${PROJ_HOME}/target/aarch64-linux-android/release/${PROJ_BIN_NAME}" \
      "data/data/com.termux/files/home/${PROJ_BIN_NAME}"
}

main "$@"