#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/rust/aux/core.bash"

version_from_toml() {
   local -r cargo_path="${CARGO_PATH:-"${PROJ_HOME}/Cargo.toml"}"
   cat "$cargo_path" \
      | grep version \
      | head -n1 \
      | awk '{print $NF}' \
      | tr -d '"' \
      | tr -d "'"
}

main() {
   cd "$PROJ_HOME"
   
   version="${1:-$(version_from_toml)}"
   log::info "version: $version..."
   sleep 2

   git tag -a "v${version}"
   git push origin --tags
}

main "$@"