#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/windows/aux/core.sh"
source "${DOTFILES}/scripts/core/log.sh"

##? Create app shortcuts
##?
##? Usage:
##?    app-shortcuts

doc::maybe_help "$@"

pretty() {
   sed 's/.exe//' \
      | sed 's/portable//gI' \
      | sed -E 's/[0-9]+\..*//' \
      | sed -E 's/[-_]+ *$//'
}

name_from_folder() {
   grep -Eo '[^\/]+/[^/]+$' \
      | cut -d'/' -f2
}

create_link() {
   local -r exe="$1"
   local -r dest_dir="$STARTMENU_PATH"
   local -r folder_name="$(name_from_folder "$exe" | pretty)"
   local -r exe_name="$(basename "$exe" | pretty)"
   local -r dest_name="${folder_name}_${exe_name}"

   echo dot windows shortcut \
      "$exe" \
      "$dest_dir" \
      "$dest_name"
}

all_exes() {
   find "$PORTABLE_PATH" -maxdepth 2 -iname '*.exe'
}

_main() {
   for exe in $(all_exes); do
      log::note "$exe"
      if echo "$exe" | grep -q "install"; then
         log::warning "Skipped"
      else
         create_link "$exe" || true
      fi
      echoerr
   done
}

_main "$@"