#!/usr/bin/env bash
# vim: filetype=sh
# set -euo pipefail

# source $DOTFILES/scripts/core/main.sh 

##? Performs keybinding-related operations
 #? 0.1.0
##?
##? Usage:
##?    khdx desktop (next|previous)

#eval_docopts "$@"

function move_to_desktop() {
	local target_desktop="$1"
	khd -p "alt - ${target_desktop}" &>/dev/null
}

echo 3
# move_to_desktop 2
exit 0

if $desktop; then
	current_desktop="$(chunkc tiling::query --desktop id)"
	total_desktops=$(defaults read com.apple.spaces | grep name | wc -l)
	if $previous && [[ $current_desktop > 1 ]]; then
		move_to_desktop $(expr $current_desktop - 1)
	elif $next && [[ $current_desktop < total_desktops ]]; then
		move_to_desktop $(expr $current_desktop + 1)
	fi
fi
