#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source $DOTFILES/scripts/core/main.sh 
source $DOTFILES/scripts/environment/core.sh

##? Updates submodules, dotfiles and attempts to do some setup
 #? 0.3.0
##?
##? Usage:
##?    dotfiles

docopts "$@"

DOTBOT_DIR="modules/dotbot"
DOTBOT_BIN="bin/dotbot"

function main() {
  update_dotfiles_pre;
  update_dotfiles_common;
  is_osx && { update_dotfiles_osx; }
  is_linux && { update_dotfiles_linux; }
  is_arm && { update_dotfiles_arm; }
  update_dotfiles_pos;
}

update_dotfiles_pre() {

  echo "Setting folder architecture..."
  mkdir -p "$DOTFILES/local/bin"
  pushd . > /dev/null
  cd $DOTFILES

  echo "Attempting to update submodules..."
  (git pull && git submodule init && git submodule update && git submodule status && \
    cd "${DOTFILES}" && git submodule update --init --recursive "${DOTBOT_DIR}" || true)

}

update_dotfiles() {

  CONFIG="$DOTFILES/scripts/db/$1"
  shift

  echo
  "${DOTFILES}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${DOTFILES}" -c "${CONFIG}" "${@}" 
  echo

}

update_dotfiles_pos() {

  set +e

  # Neovim
  echo "Installing neovim plugins..."
  nvim +silent +PlugInstall +qall > /dev/null

  # Tmux
  echo "Installing tpm plugins..."
  export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins/"
  bash "${TMUX_PLUGIN_MANAGER_PATH}tpm/bin/install_plugins" > /dev/null
  bash "${TMUX_PLUGIN_MANAGER_PATH}tpm/bin/update_plugins" all > /dev/null

  # ZPlug
  echo "Installing ZPlug plugins..."
  zplug install 2> /dev/null

  set -e

  # Cleanup
  popd > /dev/null

}

update_dotfiles_common() {
  update_dotfiles "conf.yaml"
}

update_dotfiles_osx() {
  echo "Adding necessary files for OSX"
  update_dotfiles "conf.osx.yaml"
}

update_dotfiles_linux() {
  echo "No custom config for Linux yet"
}

update_dotfiles_arm() {
  echo "Adding necessary files for ARM"
  update_dotfiles "conf.arm.yaml"
}

main "$@"