#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source $DOTFILES/scripts/core/main.sh 

##? Checks for command availability
 #? 0.2.1
##?
##? Usage:
##?    health

eval_docopts "$@"

CODE=0

function check_command_available() {
  local cmd="$1"
  if command_exists "$cmd"; then
    success "$cmd"
  else
    error "$cmd"
    CODE=$(($CODE + 1))
  fi
}

function check_gnu_command_available() {
  local cmd
  if is_osx; then
    cmd="g$1"
  else
    cmd="$1"
  fi
  check_command_available "$cmd"
}

function check_commands() {
  local cmds="$1"
  for cmd in $cmds; do
      check_command_available "$cmd"
  done
}

function check_gnu_commands() {
  local cmds="$1"
  for cmd in $cmds; do
      check_gnu_command_available "$cmd"
  done
}

header "CLIs"
check_commands "git zsh tmux nvim fasd ruby python ag"

if is_osx; then
  echo
  header "GNU commands"
  check_gnu_commands "sed grep" true
fi

exit $CODE