#!/usr/bin/env bash
set -euo pipefail

export DOTFILES="${DOTFILES:-$HOME/.dotfiles}"

##? Setups the environment
#?? 0.1.1
##?
##? Usage:
##?    init
##?    init brew

_dot() {
   "$DOTFILES/bin/dot" "$@"
}

platform::command_exists() {
   type "$1" &>/dev/null
}

platform::is_osx() {
   [[ $(uname -s) == "Darwin" ]]
}

install_brew_osx() {
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_brew_linux() {
   sudo apt update && sudo apt-get install -y build-essential curl file git \
      || sudo yum groupinstall 'Development Tools' && sudo yum install curl file git
   sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
   test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
   test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
   test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
   echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
}

install_brew() {
   if ! platform::command_exists brew && ! fs::is_dir /home/linuxbrew; then
      echo "Installing brew"
      if platform::is_osx; then
         install_brew_osx
      else
         install_brew_linux
      fi
   fi
}

install_essentials() {
   if ! platform::command_exists git; then
      echo "Installing git"
      brew install git
   elif ! platform::command_exists python; then
      echo "Installing python"
      brew install python
   fi
}

clone_repo() {
   git clone https://github.com/denisidoro/dotfiles.git "$DOTFILES"
}

# Displays help if requested
if [[ ${1:-} == "-h" ]] || [[ ${1:-} == "--help" ]]; then
   grep "^##?" "$0" | cut -c 5-
   exit 0
fi

# Shortcut for installing brew
if [[ ${1:-} == "brew" ]]; then
   install_brew
fi

# Pushes the current directory to the stack
pushd . >/dev/null

echo -e "\e[36mdenisidoro's dotfiles\e[0m\n"

# Prompt confirmation
echo "This script is untested. Use it at your own risk!"
read -r -p "Do you want to continue? (Y/n) " response
response=${response,,}
if [[ $response =~ ^(yes|y| ) ]] || [ -z $response ]; then
   sudo echo "Proceeding with installation..."
else
   exit
fi

set +e
install_brew
install_essentials
set -e

if [ -f "$DOTFILES/bin/dot" ]; then
   :
elif [ -f "$DOTFILES" ]; then
   echo "Backing up existing .dotfiles folder and cloning new .dotfiles..."
   local old_dotfiles=$(mktemp -u -d "${DOTFILES}_XXXX")
   mv "$DOTFILES" "$old_dotfiles"
   clone_repo
else
   echo "No .dotfiles folder found. Installing dependencies and cloning .dotfiles..."
   clone_repo
fi

cd "$DOTFILES"

# install necessary dependencies
_dot environment install batch nano

# invoke dotfiles symlinking
_dot environment update

# cleanup
popd >/dev/null
