#!/usr/bin/env bash
set -euo pipefail

export DOTFILES="${DOTFILES:-$HOME/.dotfiles}"
REPO="https://github.com/denisidoro/dotfiles.git"

##? Setups the environment
#?? 0.3.0
##?
##? Usage:
##?    init

_dot() {
   "${DOTFILES}/bin/dot" -d "$@"
}

clone_repo() {
   git clone "$REPO" "$DOTFILES"
}

# Pushes the current directory to the stack
pushd . >/dev/null

if [ -f "$DOTFILES/bin/dot" ]; then
   :
elif [ -f "$DOTFILES" ]; then
   echo "Backing up existing .dotfiles folder and cloning new .dotfiles..."
   old_dotfiles=$(mktemp -u -d "${DOTFILES}_XXXX")
   mv "$DOTFILES" "$old_dotfiles"
   clone_repo
else
   echo "No .dotfiles folder found. Installing dependencies and cloning .dotfiles..."
   clone_repo
fi

cd "$DOTFILES"

# call setup
_dot environment update

# cleanup
popd >/dev/null
