#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source $DOTFILES/scripts/core/main.sh 
source $DOTFILES/scripts/environment/core.sh 

##? Setups an OSX environment
 #? 0.1.1
##?
##? Usage:
##?    osx apps
##?    osx dev (android|clojure)

docopts "$@"

$apps && { 
	cask_install "cask-apps"; 
};
$dev && {
	$android && { cask_install "cask-java" "cask-android"; }
	$clojure && { cask_install "cask-java" && brew_install "leiningen"; }
}

