#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/environment/core.sh"

##? Setups resources
#?? 0.1.1
##?
##? Usage:
##?    resources fontawesome

docs::eval "$@"

if $fontawesome; then

   url="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
   css="$HOME/.dotfiles/wm/nerdbar/font-awesome.min.css"

   if [[ ! -f "$css" ]]; then
      mkdir -p "$(dirname "$css")"
      curl -s "$url" -o "$css"
   fi

   echo "$css"

fi
