#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null && pwd)"
export DOTFILES="${DOTFILES:-$ROOT_DIR}"
source "${DOTFILES}/scripts/core/main.sh"

##? Run tests
##?
##? Usage:
##?    test <suite>

suite="$1"
bash "${DOTFILES}/scripts/environment/tests/${suite}.sh"

