#!/usr/bin/env bash
set -euo pipefail

export DOTFILES="${DOTFILES:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null && pwd)}"
source "${DOTFILES}/scripts/core/main.sh"

##? Run tests
##?
##? Usage:
##?    test <suite>

suite="$1"
bash "${DOTFILES}/scripts/environment/tests/${suite}.sh"

