#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"
source "${DOTFILES}/scripts/environment/aux/update.sh"

##? Updates submodules, dotfiles and attempts to do some setup
#?? 0.3.0
##?
##? Usage:
##?    dotfiles

git_info="$(get_git_info)"
log::note "Updating dotfiles\n${git_info}\n"
echo

tags="$(platform::tags)"
log::note "Current config: $tags"
echo

set +e

setup_sudo_fallback
update_submodules 2>/dev/null || true
setup_folders_and_files
setup_git_credentials
setup_docopts
replace_file "${HOME}/.bashrc"
replace_file "${HOME}/.zshrc"

log::note "Setting symlinks..."
update_dotfiles_common
has_tag "$tags" "osx" && { update_dotfiles_osx; }
has_tag "$tags" "linux" && { update_dotfiles_linux; }
has_tag "$tags" "arm" && { update_dotfiles_arm; }
has_tag "$tags" "x86" && { update_dotfiles_x86; }
has_tag "$tags" "android" && { update_dotfiles_android; }
has_tag "$tags" "wsl" && { update_dotfiles_wsl; }

install_brew
install_batch "nano"
install_batch "mini"
install_batch "dev"

setup_nvim_fallback

install_nvim_plugins
install_tmux_plugins
install_zplug_plugins

set -e
