#!/usr/bin/env bash

set -e

CONFIG="scripts/conf.yaml"
DOTBOT_DIR="modules/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Updating submodules..."
echo
(git pull && git submodule init && git submodule update && git submodule status && \
  cd "${BASEDIR}" && git submodule update --init --recursive "${DOTBOT_DIR}") > /dev/null

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}" 

# Neovim
echo
echo "Installing neovim plugins..."
nvim +silent +PlugInstall +qall > /dev/null

# Tmux
echo "Installing tpm plugins..."
export TMUX_PLUGIN_MANAGER_PATH=$HOME/.tmux/plugins/
bash "${TMUX_PLUGIN_MANAGER_PATH}tpm/bin/install_plugins" > /dev/null
bash "${TMUX_PLUGIN_MANAGER_PATH}tpm/bin/update_plugins" all > /dev/null

# ZPlug
echo "Attempting to install ZPlug plugins..."
zplug install 2> /dev/null

