#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source $DOTFILES/scripts/core/main.sh 
source $DOTFILES/scripts/aux/install.sh 
source $DOTFILES/scripts/aux/setup.sh 

##? Install script
 #? 0.2.0
##?
##? Usage:
##?    install dependencies
##?    install dotfiles
##?    install osx env (apps|gnu)
##?    install osx dev (android|clojure)

eval_docopts "$@"

$dependencies && { setup; }

$dotfiles && {
  update_dotfiles_common;
  is_osx && { update_dotfiles_osx; }
}

$osx && {
  $env && {
    $apps && { cask_install "cask-apps"; }
    $gnu && { gnu_install; }
  };
  $dev && {
    $android && { cask_install "cask-java" "cask-android"; }
    $clojure && { cask_install "cask-java" && brew_install "leiningen"; }
  }
}

