#!/usr/bin/env bash

set -e

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
CONFIG="$DOTFILES/scripts/conf.yaml"
DOTBOT_DIR="modules/dotbot"
DOTBOT_BIN="bin/dotbot"

echo "Setting folder architecture..."
mkdir -p ~/.config
mkdir -p ~/.config/{nvim,git}

echo "Updating submodules..."
(git pull && git submodule init && git submodule update && git submodule status && \
  cd "${DOTFILES}" && git submodule update --init --recursive "${DOTBOT_DIR}") > /dev/null

echo
"${DOTFILES}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${DOTFILES}" -c "${CONFIG}" "${@}" 
echo

# Neovim
echo "Installing neovim plugins..."
nvim +silent +PlugInstall +qall > /dev/null

# Tmux
echo "Installing tpm plugins..."
export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins/"
bash "${TMUX_PLUGIN_MANAGER_PATH}tpm/bin/install_plugins" > /dev/null
bash "${TMUX_PLUGIN_MANAGER_PATH}tpm/bin/update_plugins" all > /dev/null

# ZPlug
echo "Attempting to install ZPlug plugins..."
zplug install 2> /dev/null

