#!/bin/bash

install_brew_if_on_osx() {
	echo "WIP"
}

install_git() {
	echo "WIP"
}

install_python() {
	echo "WIP"
}

install_docopts() {
	echo "WIP"
}

# Prompt confirmation
echo "This script is untested. Use it at your own risk!"
read -r -p "Do you want to continue? [Y/n] " response
response=${response,,} 
if [[ $response =~ ^(yes|y| ) ]] || [ -z $response ]; then
  echo "Proceeding with installation..."
else
  exit
fi

export DOTFILES="$HOME/.dotfiles"

install_brew_if_on_osx
install_git
install_python
install_docopts

# clone dotfiles repository if necessary
if [ -d "$DOTFILES" ]; then
	mv "$DOTFILES" "${DOTFILES}_tmp"
	git clone https://github.com/denisidoro/dotfiles.git "$DOTFILES"
fi

# invoke setup command
bash "$DOTFILES/scripts/install" "dependencies"