#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Open files/folders
 #? 0.1.0
##?
##? Usage:
##?    open browser <args>...
##?
##? Examples:
##?    open browser http://google.com

docs::eval "$@"

_open_browser() {
  open "$@" \
    || xdg-open "$@" \
    || google-chrome "$@" \
    || firefox "$@"
}

_open_browser "${args[@]:-}"
