#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? OSX
 #? 0.1.0
##?
##? Usage:
##?    osx hidden (show|hide)
##?    osx desktop (show|hide)
##?
##? Examples:
##?    osx hidden show
##?    osx desktop hide

docs::eval "$@"

osx::show_hidden_files() {
	defaults write com.apple.finder AppleShowAllFiles -bool true; killall Finder
}

osx::hide_hidden_files() {
	defaults write com.apple.finder AppleShowAllFiles -bool false; killall Finder
}

osx::show_desktop() {
	defaults write com.apple.finder CreateDesktop -bool true; killall Finder
}

osx::hide_desktop() {
	defaults write com.apple.finder CreateDesktop -bool false; killall Finder
}

if $hidden; then
	$show && osx::show_hidden_files || osx::hide_hidden_files
elif $desktop; then
	$show && osx::show_desktop || osx::hide_desktop
fi
