#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Shows weather info
#?? 0.1.0
##?
##? Usage:
##?    weather [<location>]

docs::eval "$@"

_format() {
   grep -v "New feature" | grep -v Follow
}

location="${location:-Sao_Paulo}"
curl -s "wttr.in/${location}" | _format
