#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? MySQL helper utilities
##?
##? Usage:
##?   mysql export <username> <database> <path>
##?   mysql import <username> <database> <path>
##?
##? Examples:
##?   mysql export root mydb backup.sql
##?   mysql import root mydb backup.sql

docs::eval "$@"

if $export; then
   mysqldump -u "$username" -p "$database" > "$path"
elif $import;
mysql -u "$username" -p "$database" < "$path"
fi