#!/usr/bin/env bash
# vim: filetype=sh
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? MySQL helper utilities
##?
##? Usage:
##?   mysql [options] export <database> <path>
##?   mysql [options] import <database> <path>
##?   mysql [options] db create <database>
##?
##? Options:
##?   -u --user       User [default: root]
##?
##? Examples:
##?   mysql export root mydb backup.sql
##?   mysql import root mydb backup.sql
##?   mysql db create mydb

docs::eval "$@"

if $db; then
   mysql -u "$user" -e "create database $database character set UTF8mb4 collate utf8mb4_bin"
elif $export; then
   mysqldump -u "$user" -p "$database" > "$path"
elif $import; then
   mysql -u "$user" -p "$database" < "$path"
fi
