#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Manager window-manager-related features
#?? 0.1.0
##?
##? Usage:
##?    apps (start|stop|toggle|restart)

docs::eval "$@"

if $toggle; then
   if ps aux | grep -q "[/]bin/khd"; then
      start=false
      stop=true
   else
      start=true
      stop=false
   fi
elif $restart; then
   start=true
   stop=true
fi

if $stop; then
   brew services stop crisidev/chunkwm/chunkwm || true
   brew services stop khd || true 
fi

if $start; then
   brew services start khd
   brew services start crisidev/chunkwm/chunkwm
fi
