#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

##? Build a Go binary using docker
#?? 0.1.0
##?
##? Usage:
##?    build <path>
##?
##? Examples:
##?    build ./myproject

docs::eval "$@"

docker run \
   -v "$(fs::realpath "$path"):/app" \
   --rm \
   golang:1.12.1-alpine3.9 \
   bash -c 'cd /app && go get -d && go build'
