#!/usr/bin/env bash
set -euo pipefail

##? Go transpiler
##? Transpiles syntax sugars
##?
##? Usage:
##?    transpile

source "${DOTFILES}/scripts/core/documentation.sh"

docs::eval_help "$@"

export PROJ_NAME="gotranspiler"
export PROJ_HOME="${DOTFILES}/scripts-rust/${PROJ_NAME}"

PROJ_BIN="${PROJ_HOME}/target/tar/${PROJ_NAME}"

if [ -f "$PROJ_BIN" ]; then
   "$PROJ_BIN" "$@"
   exit 0
fi

dot rust action release || true
"$PROJ_BIN" "$@"
