#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/scripts/core/main.sh"

JAVA_HOME=${JAVA_HOME:-"/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home"}
NATIVE_IMAGE_BIN="${NATIVE_IMAGE_BIN:-$HOME/Applications/graalvm-ee-1.0.0-rc6/Contents/Home/bin/native-image}"

cd "${DOTFILES}/scripts/clojure"
reflection="$(pwd)/reflection.json"

lein do "compile :all uberjar"
   cd "target"

   jar="$(pwd)/$(ls | grep "standalone")"
   mkdir "native" || true
   cd "native"

   JAVA_HOME="$JAVA_HOME" \
      "$NATIVE_IMAGE_BIN" \
      -H:+ReportUnsupportedElementsAtRuntime \
      "-H:ReflectionConfigurationFiles=$reflection" \
      -jar "$jar"

   bin="$(ls | grep "standalone")"
   mv "$bin" "dot"

   cd "$CALLING_DIR"
