#!/usr/bin/env bash
# vim: filetype=sh
set -uo pipefail

source "${DOTFILES}/scripts/core/documentation.sh"

##? Start a Clojure REPL using deps aliases 
#?? 0.1.0
##?
##? Usage:
##?    repl

_aliases() {
	cat "${HOME}/.clojure/deps.edn" \
	   | dot clojure data -o json \
	   | jq -r '.aliases | keys | .[]'	
}

_fzf() {
	fzf-tmux \
	   --height=15 \
	   --reverse \
	   --inline-info
}

docs::eval_help "$@"

repl_alias="$(_aliases | _fzf)"
echo "$repl_alias"
clj "-A:${repl_alias}"
