#!/bin/dash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title WhatsApp
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 💬
# @raycast.packageName Browser

# Documentation:
# @raycast.description Focus on WhatsApp tab
# @raycast.author Denis Isidoro
# @raycast.authorURL https://denisidoro.github.io

"${HOME}/dotfiles/bin/dot" osx focus-tab whatsapp
