#!/usr/bin/env bash

source "${DOTFILES}/scripts/package/aux/core.sh"

##? Set the symbolic links interactively
##?
##? Usage: 
##?   dotlink set [-i | --ignore] [-f | --force] [-b | --backup] [-v | --verbose] [-p | --create-dirs]
##? 
##? Options:
##?   -c <file>, --config <file>     Specify the configuration file to load.
##?                                  default: $HOME/.config/dot/dotrc

doc::maybe_help "$@"

main() {
   source "${DOTFILES}/scripts/link/aux/core.sh"
   dotlink_main update "$@"
}

main "$@"
