# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on: [push]

name: Tests

jobs:
  bash-tests:
    name: Bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run tests
        run: DOT_STUB_DOTRS=true PROJ_HOME=$(pwd)/rust PROJ_NAME=dotrs ./bin/dot self test suite bash

  js-tests:
    name: Javascript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
      - name: Run tests
        run: ./bin/dot self test suite js

  rust-tests:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo build
        uses: marcopolo/cargo@master
        continue-on-error: false
        with:
          command: build
          working-directory: ./rust
      - name: Run cargo test
        uses: marcopolo/cargo@master
        continue-on-error: false
        with:
          command: test
          working-directory: ./rust
      - name: Run tests
        run: DOT_SKIP_CARGO=true ./bin/dot self test suite rust

  install-tests:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Cleanup
        run: cd $HOME && for f in $(ls -a | grep '^\.'); do rm "$f" || true; done
      - name: dot self install
        run: EDITOR=cat TERM=dumb DOT_INSTALL_SKIP_UPDATE=true DOT_DOCOPT=python DOT_FRE=false DOT_FZF=false DOT_NAVI=false DOT_ZIM=false DOT_STARSHIP=false ./bin/dot self install
      - name: dot version
        run: source $HOME/.bashrc && dot --version | grep "$(date +'%Y')" 